import 'dart:convert';
import 'dart:io';

import 'package:crm3_baf_ops/core/serialization/persisted_data_reader.dart';
import 'package:crm3_baf_ops/features/abnormalities/data/abnormality_model.dart';
import 'package:crm3_baf_ops/features/audit/models/audit_event_model.dart';
import 'package:crm3_baf_ops/features/audit/repositories/audit_repository.dart';
import 'package:crm3_baf_ops/features/planned_maintenance/data/job_template_model.dart';
import 'package:flutter_test/flutter_test.dart';

// Generated by functions/test/helpers/produceRetainedQueueAudits.cjs from the
// real dispatcher and handlers. Backend tests compare fresh output to this
// fixture; this consumer remains runnable in Flutter-only CI jobs.
void main() {
  final rows =
      (jsonDecode(
                File(
                  'test/fixtures/retained_queue_dispatcher_audits.json',
                ).readAsStringSync(),
              )
              as List)
          .cast<Map<String, dynamic>>();
  final expected = [
    ('abnormality_type', AuditAction.create, 'admin'),
    ('job_template', AuditAction.create, 'si'),
    ('job_execution', AuditAction.update, 'worker'),
    ('abnormality_type', AuditAction.delete, 'admin'),
  ];

  test('fixture contains all four actual dispatcher audit outcomes', () {
    expect(rows, hasLength(expected.length));
    expect(rows.map((row) => row['documentId']).toSet(), hasLength(4));
  });

  for (var i = 0; i < expected.length; i++) {
    final (entity, action, actor) = expected[i];
    test(
      'strict Dart audit reader accepts dispatcher $entity ${action.name}',
      () {
        final row = rows[i];
        final raw = Map<String, dynamic>.from(row['data'] as Map);
        final event = decodePersistedAuditEvent(
          raw,
          documentId: row['documentId'] as String,
        );
        expect(event.remoteDocumentId, row['documentId']);
        expect(event.entityType, entity);
        expect(event.action, action);
        expect(event.performedByUid, actor);
        expect(event.severity, AuditSeverity.low);
        expect(event.timestamp, DateTime.utc(2026, 9, 27, 1));
        expect(event.isSynced, true);
        expect(event.after!['firestoreId'], event.entityId);
        expect(event.after!['version'], action == AuditAction.create ? 1 : 2);
        expect(event.before == null, action == AuditAction.create);
        expect(raw['projectId'], 'demo-crm3-cf01');
        expect(
          raw['payloadFingerprint'],
          matches(RegExp(r'^sha256:[0-9a-f]{64}$')),
        );
        // The nested evidence must also remain usable by actual business readers.
        switch (entity) {
          case 'abnormality_type':
            final record = AbnormalityType.fromMap(
              event.after!,
              event.entityId,
            );
            expect(record.isDeleted, action == AuditAction.delete);
            expect(record.createdByUid, 'admin');
            expect(
              record.updatedAt,
              DateTime.utc(2026, 9, 27, 0, 1, 0, 234, 567),
            );
            if (action == AuditAction.delete) {
              expect(record.deletedByUid, actor);
              expect(event.before!['isDeleted'], false);
            }
          case 'job_template':
            final record = JobTemplate.fromMap(event.after!, event.entityId);
            expect(record.createdByUid, 'si');
            expect(record.assignedAgencies, ['mechanical']);
            expect(
              record.createdAt,
              DateTime.utc(2026, 9, 27, 0, 0, 0, 123, 456),
            );
          case 'job_execution':
            final record = JobExecution.fromMap(event.after!, event.entityId);
            expect(record.remarks, 'Inspection recorded');
            expect(record.isCompleted, false);
            expect(record.assignedByUid, 'si');
            expect(event.before!['remarks'], isNull);
            expect(event.before!['assignedByUid'], record.assignedByUid);
        }
      },
    );
  }

  test(
    'missing severity in server audit cannot become a default successful row',
    () {
      final raw = Map<String, dynamic>.from(rows.first['data'] as Map)
        ..remove('severity');
      expect(
        () => decodePersistedAuditEvent(raw, documentId: 'missing-severity'),
        throwsA(isA<PersistedDataFormatException>()),
      );
    },
  );

  test('malformed before evidence is rejected rather than discarded', () {
    final raw = Map<String, dynamic>.from(rows[2]['data'] as Map)
      ..['beforeJson'] = '["not an object"]';
    expect(
      () => decodePersistedAuditEvent(raw, documentId: 'malformed-evidence'),
      throwsA(isA<PersistedDataFormatException>()),
    );
  });
}
