// GENERATED FILE. Source: governance/maintenance_workflow_policy_v1.json
// Do not edit manually.
export const WORKFLOW_POLICY_SCHEMA_VERSION = 3 as const;
export const WORKFLOW_POLICY_ID = "crm3-maintenance-workflow-v3" as const;
export const ONLINE_ONLY_LIFECYCLE_COMMANDS = true as const;
export const LANE_SET_FINALIZER_ROLES = ["admin","si","contractSupervisor"] as const;
export const MODULE_LIFECYCLE_MODERATOR_ROLES = ["admin","si","contractSupervisor","shiftSupervisor"] as const;
export const COMMAND_AUTHORITY_ROLES = Object.freeze({"finalizeLaneSet":["admin","si","contractSupervisor"],"manageLanePopulation":["admin","si","contractSupervisor"],"cancelWorkflow":["admin","si","contractSupervisor"],"finalizeJob":["admin","si","contractSupervisor","shiftSupervisor"],"markConditionDue":["admin","si","operations","shiftSupervisor"],"deployEquipment":["admin","si","operations","shiftSupervisor"],"reconcileEquipment":["admin","si"],"prepareRedLane":["admin","si","contractSupervisor","shiftSupervisor","seniorElectrical","seniorMechanical","seniorInstrumentation","seniorRefractory"],"reopenWorkflowModule":["admin","si","contractSupervisor","shiftSupervisor"],"raiseComplianceCoordination":["admin","si","contractSupervisor","shiftSupervisor"],"confirmCriticalAlarmSupport":["admin","si"],"resolveCriticalAlarm":["admin","si"],"manageCriticalAlarmContacts":["admin"]}) as Readonly<Record<string, readonly string[]>>;
export const CRITICAL_ALARM_DEFINITIONS = Object.freeze({"fire":{"key":"fire","name":"Fire","criticalityKey":"highest","criticalityRank":1},"majorGasLeakage":{"key":"majorGasLeakage","name":"Major gas leakage","criticalityKey":"highest","criticalityRank":1},"blast":{"key":"blast","name":"Blast","criticalityKey":"highest","criticalityRank":1},"nitrogenFailure":{"key":"nitrogenFailure","name":"Nitrogen failure","criticalityKey":"critical","criticalityRank":2},"hotWellPumpFailure":{"key":"hotWellPumpFailure","name":"Hot well pump failure","criticalityKey":"critical","criticalityRank":2}}) as Readonly<Record<string, Readonly<{key:string;name:string;criticalityKey:"highest"|"critical";criticalityRank:number}>>>;
export const WORKFLOW_ROLE_UNIVERSE = ["admin","si","contractSupervisor","seniorElectrical","seniorMechanical","seniorInstrumentation","operations","shiftSupervisor","refractory","seniorRefractory"] as const;
export const RED_APPLICABLE_ASSET_TYPES = new Set(["base","furnace"]);
export const STAND_PREPARATION_ASSET_TYPES = new Set(["furnace"]);
export const WORKFLOW_CLOCKS_MINUTES = Object.freeze({"criticalAcknowledgement":30,"normalAcknowledgement":240,"complianceAcknowledgement":240,"complianceAfterCondition":480});
export const LANE_POLICY = Object.freeze({"elec":{"key":"elec","code":"ELEC","name":"Electrical","ackRoles":["admin","si","seniorElectrical"],"workRoles":["admin","si","seniorElectrical"],"closeRoles":["admin","si","seniorElectrical"]},"mech":{"key":"mech","code":"MECH","name":"Mechanical","ackRoles":["admin","si","seniorMechanical"],"workRoles":["admin","si","seniorMechanical"],"closeRoles":["admin","si","seniorMechanical"]},"inst":{"key":"inst","code":"I&A","name":"Instrumentation & Automation","ackRoles":["admin","si","seniorInstrumentation"],"workRoles":["admin","si","seniorInstrumentation"],"closeRoles":["admin","si","seniorInstrumentation"]},"oprn":{"key":"oprn","code":"OPRN","name":"Operations","ackRoles":["admin","si","operations","shiftSupervisor"],"workRoles":["admin","si","operations","shiftSupervisor"],"closeRoles":["admin","si","shiftSupervisor"]},"emd":{"key":"emd","code":"EMD","name":"EMD","ackRoles":["admin","si"],"workRoles":["admin","si"],"closeRoles":["admin","si"],"delegated":true,"delegationBasis":"plant-v1-emd-admin-si-coordination"},"red":{"key":"red","code":"RED","name":"Refractory Engineering Department","ackRoles":["admin","si","refractory","seniorRefractory"],"workRoles":["admin","si","refractory","seniorRefractory"],"closeRoles":["admin","si","seniorRefractory"]},"shared":{"key":"shared","code":"SHARED","name":"Shared / Safety / Administration","ackRoles":["admin","si","contractSupervisor","shiftSupervisor"],"workRoles":["admin","si","contractSupervisor","shiftSupervisor"],"closeRoles":["admin","si","contractSupervisor","shiftSupervisor"],"delegated":true,"delegationBasis":"plant-v2-shared-coordination"}}) as Readonly<Record<string, Readonly<{key:string;code:string;name:string;ackRoles:readonly string[];workRoles:readonly string[];closeRoles:readonly string[];delegated?:boolean;delegationBasis?:string}>>>;
export const MODULE_DISCIPLINE_LANE_MAP = Object.freeze({"electrical":"elec","mechanical":"mech","instrumentation":"inst","operations":"oprn","shiftInCharge":"oprn","emd":"emd","refractory":"red","safety":"shared","admin":"shared","shared":"shared","others":"shared"}) as Readonly<Record<string, string>>;
export const MODULE_DISCIPLINE_WORK_ROLES = Object.freeze({"electrical":["admin","si","contractSupervisor","shiftSupervisor","seniorElectrical"],"mechanical":["admin","si","contractSupervisor","shiftSupervisor","seniorMechanical"],"instrumentation":["admin","si","contractSupervisor","shiftSupervisor","seniorInstrumentation"],"operations":["admin","si","contractSupervisor","shiftSupervisor","operations"],"shiftInCharge":["admin","si","contractSupervisor","shiftSupervisor"],"emd":["admin","si"],"refractory":["admin","si","contractSupervisor","shiftSupervisor","refractory","seniorRefractory"],"safety":["admin","si","contractSupervisor","shiftSupervisor"],"admin":["admin","si","contractSupervisor","shiftSupervisor"],"shared":["admin","si","contractSupervisor","shiftSupervisor"],"others":["admin","si","contractSupervisor","shiftSupervisor","seniorRefractory"]}) as Readonly<Record<string, readonly string[]>>;
export const MODULE_DISCIPLINE_SUBMIT_ROLES = Object.freeze({"electrical":["admin","si","contractSupervisor","shiftSupervisor","seniorElectrical"],"mechanical":["admin","si","contractSupervisor","shiftSupervisor","seniorMechanical"],"instrumentation":["admin","si","contractSupervisor","shiftSupervisor","seniorInstrumentation"],"operations":["admin","si","contractSupervisor","shiftSupervisor","operations"],"shiftInCharge":["admin","si","contractSupervisor","shiftSupervisor"],"emd":["admin","si"],"refractory":["admin","si","contractSupervisor","shiftSupervisor","refractory","seniorRefractory"],"safety":["admin","si","contractSupervisor","shiftSupervisor"],"admin":["admin","si","contractSupervisor","shiftSupervisor"],"shared":["admin","si","contractSupervisor","shiftSupervisor"],"others":["admin","si","contractSupervisor","shiftSupervisor","seniorRefractory"]}) as Readonly<Record<string, readonly string[]>>;
