const {Timestamp} = require('firebase-admin/firestore');

// Sanitized schema shape observed in a persisted issue-origin Base case.
// Firestore stores the nested association instants as native Timestamps.
function baseAssociationCase(issueId = 'ticket-1') {
  const warningId = `issue_${issueId}`;
  const abnormalityId = `issue_quality_${issueId}`;
  const createdAt = Timestamp.fromDate(new Date('2026-09-14T02:27:55.163Z'));
  const affectedAssets = [{
    assetType: 'base',
    assetNumber: 12,
    assetHierarchyRef: {
      schemaVersion: 4,
      scope: 'componentDefinitionOnAsset',
      assetClassId: 'base-class',
      assetClassCode: 'BASE',
      assetClassName: 'Base',
      assetInstanceId: 'base-12',
      assetInstanceName: 'Base 12',
      assetInstanceVersion: 1,
      assetNumber: 12,
      nodeId: 'base-seal',
      nodeName: 'Base seal (O-ring)',
      nodeVersion: 1,
      componentInstanceId: null,
      componentInstanceVersion: null,
      componentTag: null,
      hierarchyPath: ['Structure, sealing and charge support', 'Base seal (O-ring)'],
      ownershipStatus: 'provisional',
      ownerDiscipline: 'Mechanical',
      accountableRoleKeys: ['seniorMechanical'],
      innerCoverAssociation: {
        baseAssetInstanceId: 'base-12',
        baseAssetNumber: 12,
        positionState: 'noneLinked',
        innerCoverId: null,
        innerCoverSerialNumber: null,
        linkageId: null,
        assignmentVersion: null,
        linkedAt: null,
        eventAt: Timestamp.fromDate(new Date('2026-09-14T02:26:18.158Z')),
        confirmedAt: createdAt,
        confirmedByUid: 'ops-1',
        confirmedByName: 'Operations One',
      },
    },
  }];
  const warning = {
    schemaVersion: 1,
    warningId,
    sourceType: 'issue',
    sourceId: issueId,
    sourceVersion: 1,
    sourceChargeNo: 12047,
    sourceSummary: 'Unlisted issue',
    sourceSeverity: 'standard',
    warningReason: 'Atmosphere interruption recorded during trial.',
    affectedAssets,
    component: 'Base seal (O-ring)',
    status: 'open',
    closureRequestReason: null,
    closureRequestedAt: null,
    closureRequestedByUid: null,
    closureRequestedByName: null,
    closedAt: null,
    closedByUid: null,
    closedByName: null,
    closureDisposition: null,
    linkedReannealingChargeNos: [],
    decisionReason: null,
    createdAt,
    createdByUid: 'ops-1',
    createdByName: 'Operations One',
    updatedAt: createdAt,
    updatedByUid: 'ops-1',
    updatedByName: 'Operations One',
    version: 1,
  };
  const abnormality = {
    firestoreId: abnormalityId,
    sourceChargeNo: warning.sourceChargeNo,
    abnormalityTypeId: 'UNLISTED',
    abnormalityTypeTitle: 'Atmosphere disturbed during furnace removal',
    abnormalityTypeCode: 'UNLISTED',
    category: 'process',
    severity: 'high',
    affectedAssets: [{assetType: 'base', assetNumber: 12}],
    affectedAssetHierarchyRefs: affectedAssets,
    component: warning.component,
    observedReason: warning.warningReason,
    description: 'Created from a governed maintenance issue.',
    possibleRootReasonCategory: 'unknown',
    possibleRootReasonNotes: null,
    reannealingStatus: 'pendingDecision',
    reannealedToChargeNo: null,
    loggedAt: createdAt,
    updatedAt: createdAt,
    loggedByUid: 'ops-1',
    loggedByName: 'Operations One',
    updatedByUid: 'ops-1',
    updatedByName: 'Operations One',
    linkedTicketFirestoreId: issueId,
    linkedExecutionFirestoreId: null,
    version: 1,
    isDeleted: false,
    deletedAt: null,
    deletedByUid: null,
    deletedByName: null,
    deleteReason: null,
    _globalPullServerUpdatedAt: Timestamp.fromDate(new Date('2026-09-14T02:27:56.320Z')),
  };
  const issue = {
    qualityWarningId: warningId,
    qualityAbnormalityId: abnormalityId,
    chargeQualityCaseId: warningId,
  };
  return {warning, abnormality, issue, warningId, abnormalityId, issueId};
}

module.exports = {baseAssociationCase};
