'use strict';
// PRIVATE read-only closure proposal; no deployment or construction authority.
const zlib=require('node:zlib');
const a=require('./backendRuntimeAdmission31.cjs');
const {need,eq,hash,time,git,object,fileBinding,committed,ancestor}=a.helpers;
function endpointRuntimeHashes31({sourceArchiveHash,inputs,runtime,names,source}){
 const fs=require('./backendRuntimeEvidenceAccess31.cjs').fs,path=require('./backendRuntimeEvidenceAccess31.cjs').path;need(typeof sourceArchiveHash==='string'&&/^[0-9a-f]{40}$/.test(sourceArchiveHash),'Actual package-source hash required');
 need(inputs.schemaVersion===1&&['firebase-cli-prepared-backend-hash-inputs','firebase-cli-approved-intended-hash-inputs'].includes(inputs.documentType)&&inputs.codebase==='default'&&inputs.sourceArchiveHash===sourceArchiveHash,'Original prepared backend hash inputs required');eq(inputs.source,source,'Prepared input source differs');eq(inputs.sourceBefore,source,'Prepared input initial source differs');eq(inputs.sourceAfter,source,'Prepared input final source differs');
 const env=inputs.environmentVariables;need(env&&typeof env==='object'&&!Array.isArray(env)&&Object.keys(env).length<=200&&Object.entries(env).every(([k,v])=>/^[A-Za-z_][A-Za-z0-9_]*$/.test(k)&&typeof v==='string'),'Exact private codebase environment input required');
 eq(Object.keys(inputs.endpoints??{}).sort(),names,'Prepared endpoint population differs');
 const lib=path.dirname(path.dirname(runtime.cliEntrypoint)),producers={apply:path.join(lib,'deploy/functions/cache/applyHash.js'),hash:path.join(lib,'deploy/functions/cache/hash.js'),secrets:path.join(lib,'functions/secrets.js')};eq(Object.keys(runtime.endpointHashProducerSha256??{}).sort(),Object.keys(producers).sort(),'Actual endpoint hash producer bindings required');for(const [key,file]of Object.entries(producers))need(hash(fs.readFileSync(file))===runtime.endpointHashProducerSha256[key],'Endpoint hash producer differs');
 const api=require(require('./backendRuntimeEvidenceAccess31.cjs').resolveOriginal(producers.hash)),envHash=api.getEnvironmentVariablesHash({environmentVariables:env}),out={};for(const name of names){const e=inputs.endpoints[name];need(e?.id===name&&e.platform==='gcfv2'&&e.project==='crm3-baf-ops-b8638'&&e.region==='asia-south1'&&Array.isArray(e.secretEnvironmentVariables)&&e.secretEnvironmentVariables.length<=100,'Exact prepared endpoint identity/secrets metadata required');need(e.secretEnvironmentVariables.every(v=>v&&typeof v.key==='string'&&typeof v.secret==='string'&&typeof v.projectId==='string'&&typeof v.version==='string'&&/^[1-9][0-9]*$/.test(v.version))&&new Set(e.secretEnvironmentVariables.map(v=>v.key)).size===e.secretEnvironmentVariables.length,'Secret declaration metadata invalid');out[name]=api.getEndpointHash(sourceArchiveHash,envHash,api.getSecretsHash(e));}return out;
}
function bindPreparedHashInputsToControls31({inputs,raw,names,expectedHashes}){
 const rows=raw.functions.flatMap(p=>JSON.parse(p.bodyText).functions??[]);eq(rows.map(r=>r.name.split('/').at(-1)).sort(),names,'Hash-input raw controls population differs');for(const row of rows){const name=row.name.split('/').at(-1);for(const[k,v]of Object.entries(inputs.environmentVariables))need(row.serviceConfig?.environmentVariables?.[k]===v,'Prepared codebase env differs from preserved serving controls');const normal=xs=>xs.map(x=>({key:x.key,projectId:x.projectId,secret:x.secret,version:x.version})).sort((x,y)=>x.key.localeCompare(y.key));eq(normal(row.serviceConfig?.secretEnvironmentVariables??[]),normal(inputs.endpoints[name].secretEnvironmentVariables),'Prepared secret-version metadata differs from serving controls');need(row.labels?.['firebase-functions-hash']===expectedHashes[name],'Raw controls endpoint label differs');}
}
function actualArchiveInventory31({repoRoot,sourceCommit,buildRoot,runtime}){
 const fs=require('./backendRuntimeEvidenceAccess31.cjs').fs,path=require('./backendRuntimeEvidenceAccess31.cjs').path,{execFileSync}=require('node:child_process');
 const config=object(git(repoRoot,['show',sourceCommit+':firebase.json'])).functions;need(Array.isArray(config)&&config.length===1&&config[0].source==='functions'&&config[0].codebase==='default','Fixed Functions packaging configuration required');
 const lib=path.dirname(path.dirname(runtime.cliEntrypoint)),files={prepare:path.join(lib,'deploy/functions/prepareFunctionsUpload.js'),enumerator:path.join(lib,'fsAsync.js')};
 eq(Object.keys(runtime.packagingProducerSha256??{}).sort(),['enumerator','prepare'],'Pinned actual packaging producer bindings required');for(const[name,file]of Object.entries(files))need(hash(fs.readFileSync(file))===runtime.packagingProducerSha256[name],'Installed packaging producer differs');
 const script="const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');const [mod,root,ignore,mapFile,mapSha,cliRoot]=process.argv.slice(1);const raw=fs.readFileSync(mapFile);if(crypto.createHash('sha256').update(raw).digest('hex').toUpperCase()!==mapSha)throw Error('CLI map differs');const bindings=JSON.parse(raw),prefix=fs.realpathSync(cliRoot),Module=require('node:module'),load=Module._load;Module._load=function(id,parent,main){const resolved=Module._resolveFilename(id,parent,main);if(path.isAbsolute(resolved)){const rel=path.relative(prefix,fs.realpathSync(resolved)).split(path.sep).join('/');if(!rel||rel.startsWith('..')||path.isAbsolute(rel)||!Object.hasOwn(bindings,rel)||crypto.createHash('sha256').update(fs.readFileSync(resolved)).digest('hex').toUpperCase()!==bindings[rel])throw Error('Unbound CLI dependency before evaluation: '+rel);}return load.apply(this,arguments);};require(mod).readdirRecursive({path:root,ignoreStrings:JSON.parse(ignore)}).then(rows=>{const out={};for(const row of rows){const rel=path.relative(root,row.name).split(path.sep).join('/');if(Object.hasOwn(out,rel))throw Error('duplicate archive member');const b=fs.readFileSync(row.name);out[rel]={sha256:crypto.createHash('sha256').update(b).digest('hex').toUpperCase(),bytes:b.length};}process.stdout.write(JSON.stringify(out));}).catch(e=>{process.stderr.write(e.message);process.exitCode=1});";
 const ignore=[...config[0].ignore,'firebase-debug.log','firebase-debug.*.log','.runtimeconfig.json'];
 return object(execFileSync(require('./backendRuntimeEvidenceAccess31.cjs').archiveInterpreter(runtime),['--no-global-search-paths','-e',script,require('./backendRuntimeEvidenceAccess31.cjs').resolveOriginal(files.enumerator),require('./backendRuntimeEvidenceAccess31.cjs').resolveOriginal(path.join(buildRoot,'functions')),JSON.stringify(ignore),require('./backendRuntimeEvidenceAccess31.cjs').resolveOriginal(runtime.cliFileBindings.path),runtime.cliFileBindings.sha256,require('./backendRuntimeEvidenceAccess31.cjs').resolveOriginal(path.dirname(path.dirname(path.dirname(path.dirname(runtime.cliEntrypoint)))))],{windowsHide:true,maxBuffer:32*1024*1024,env:{...process.env,NODE_OPTIONS:'',NODE_PATH:''}}));
}
function crc32(bytes){let c=0xFFFFFFFF;for(const b of bytes){c^=b;for(let n=0;n<8;n++)c=(c>>>1)^((c&1)?0xEDB88320:0);}return (c^0xFFFFFFFF)>>>0;}
function verifyArchiveBytes31(bytes,expected){
 need(Buffer.isBuffer(bytes)&&bytes.length>=22&&bytes.length<=128*1024*1024,'Bounded ZIP required');let end=-1;for(let p=bytes.length-22;p>=Math.max(0,bytes.length-65557);p--)if(bytes.readUInt32LE(p)===0x06054b50&&p+22+bytes.readUInt16LE(p+20)===bytes.length){end=p;break;}need(end>=0,'ZIP directory absent');
 need(bytes.readUInt16LE(end+4)===0&&bytes.readUInt16LE(end+6)===0,'Multi-disk ZIP excluded');const count=bytes.readUInt16LE(end+10),offset=bytes.readUInt32LE(end+16),size=bytes.readUInt32LE(end+12);need(count>0&&count<10000&&bytes.readUInt16LE(end+8)===count&&offset+size===end,'Bounded central directory required');
 const seen=new Set(),memberHashes=[];let p=offset,total=0;
 for(let i=0;i<count;i++){need(p+46<=end&&bytes.readUInt32LE(p)===0x02014b50,'Invalid central directory');const flags=bytes.readUInt16LE(p+8),method=bytes.readUInt16LE(p+10),crc=bytes.readUInt32LE(p+16),compressed=bytes.readUInt32LE(p+20),length=bytes.readUInt32LE(p+24),n=bytes.readUInt16LE(p+28),extra=bytes.readUInt16LE(p+30),comment=bytes.readUInt16LE(p+32),local=bytes.readUInt32LE(p+42);need(!(flags&1)&&[0,8].includes(method)&&p+46+n+extra+comment<=end,'Unsupported ZIP member');const name=bytes.subarray(p+46,p+46+n).toString('utf8');need(name&&!name.includes('\\')&&!name.includes(':')&&!name.startsWith('/')&&name.split('/').every(v=>v&&v!=='.'&&v!=='..')&&!seen.has(name),'Unsafe/duplicate ZIP member');seen.add(name);need(expected[name]&&local+30<=offset&&bytes.readUInt32LE(local)===0x04034b50,'Unknown member/local header');const localName=bytes.readUInt16LE(local+26),localExtra=bytes.readUInt16LE(local+28),start=local+30+localName+localExtra;need(bytes.subarray(local+30,local+30+localName).toString('utf8')===name&&bytes.readUInt16LE(local+8)===method&&start+compressed<=offset,'Local ZIP member mismatch');total+=length;need(total<=256*1024*1024,'ZIP expansion exceeds bound');const raw=method===0?bytes.subarray(start,start+compressed):zlib.inflateRawSync(bytes.subarray(start,start+compressed),{maxOutputLength:length+1});need(raw.length===length&&crc32(raw)===crc&&hash(raw)===expected[name].sha256&&raw.length===expected[name].bytes,'ZIP member bytes/CRC differ: '+name);memberHashes.push(require('node:crypto').createHash('sha1').update(raw).digest('hex'));p+=46+n+extra+comment;}
 need(p===end,'Extra central directory bytes');eq([...seen].sort(),Object.keys(expected).sort(),'ZIP member inventory differs');return {ok:true,fileCount:seen.size,archiveSha256:hash(bytes),sourceArchiveHash:require('node:crypto').createHash('sha1').update(memberHashes.sort().join('')).digest('hex')};
}
function verifyUploadedArchiveCapture31(evidenceDirectory,pointer,capture){
 const raw=fileBinding(evidenceDirectory,pointer);
 need(hash(raw)===capture.archiveSha256&&raw.length===capture.archiveBytes,'Retained uploaded ZIP differs from actual capture');
 return raw;
}
function verifyCohortControlChronology31(command,capture,controls){
 need(time(command.startedAtUtc)<=time(controls.startedAtUtc)&&time(controls.startedAtUtc)<=time(controls.completedAtUtc)&&time(controls.completedAtUtc)<=time(capture.completedAtUtc),'Fresh cohort controls were not captured before prepared comparison');
}
function verifyBackendRuntimeClosure31Inner({repoRoot,authorityRoot,approvalPointer,closurePointer,evidenceDirectory,nowUtc=new Date().toISOString()}){
 const admission=a.verifyBackendRuntimeAdmission31({repoRoot,authorityRoot,approvalPointer,evidenceDirectory,nowUtc,requireExecutionHead:false});const executionGate=require('./backendRuntimeExecutionAdmission31.cjs'),decisionRecord=committed(authorityRoot,approvalPointer,a.PATHS.approval),ownerRecord=a.helpers.child(authorityRoot,approvalPointer.commit,decisionRecord.ownerAuthorization,a.PATHS.owner);executionGate.verifyExplicitDeploymentOwner31({approval:decisionRecord,owner:ownerRecord,originalMessage:object(fileBinding(evidenceDirectory,ownerRecord.originalMessage)),source:admission.source});executionGate.rejectConsumedEvidence31({authorityRoot,approvalPointer,evidenceDirectory},decisionRecord);
 const closure=committed(authorityRoot,closurePointer,a.PATHS.closure);executionGate.rejectConsumedEvidence31({authorityRoot,approvalPointer,evidenceDirectory},{...decisionRecord,closedChain:closure});ancestor(authorityRoot,approvalPointer.commit,closurePointer.commit);a.helpers.verifyCustodyDelta(authorityRoot,admission.source.commit,closurePointer.commit);
 need(closure.schemaVersion===2&&closure.documentType==='build31-runtime-backend-deployment-closure'&&closure.profile===a.PROFILE,'Exact runtime closure type required');eq(closure.source,admission.source,'Closure source differs');eq(closure.approvalPointer,approvalPointer,'Closure approval differs');
 const start=time(closure.startedAtUtc),completed=time(closure.completedAtUtc),recorded=time(closure.recordedAtUtc),decision=time(admission.decisionAtUtc);need(decision<=start&&start<=completed&&completed<=recorded&&recorded<=time(nowUtc)&&time(admission.executionWindow.notBeforeUtc)<=start&&completed<=time(admission.executionWindow.notAfterUtc),'Actual closure execution chronology differs');need(typeof closure.sourceArchiveHash==='string'&&/^[0-9a-f]{40}$/.test(closure.sourceArchiveHash),'Actual Firebase package source hash required');
 const custodyAt=BigInt(a.helpers.gtext(authorityRoot,['show','-s','--format=%ct',closurePointer.commit]))*1000000000n;need(recorded<custodyAt+1000000000n&&custodyAt<=time(nowUtc),'Closure immutable commit predates its evidence recording');
 const scope={functionsChanged:true,rulesChanged:false,indexesChanged:false,iamChanged:false,enforcementChanged:false,manualSchedulerExecution:false,businessDataMutation:false};eq(closure.scope,scope,'Closure mutation boundary differs');
 eq(Object.keys(closure.commands??{}).sort(),['callables','events','fleet'],'Three original cohort receipts required');let previous=start;const actualCaptures=[],uploadedArchives=[];
 const covered=[];for(const phase of ['callables','events','fleet']){const r=object(fileBinding(evidenceDirectory,closure.commands[phase])),names=phase==='fleet'?admission.cohorts.schedulers:admission.cohorts[phase];eq(r.source,admission.source,'Cohort source differs');eq(r.approvalPointer,approvalPointer,'Cohort approval differs');eq(r.functions,names,'Cohort population differs');covered.push(...names);need(r.schemaVersion===2&&r.actualDeploymentPerformed===true&&r.phase===phase&&r.exitCode===0&&r.schedulerManuallyInvoked===false&&r.businessProbePerformed===false&&r.attempt===1,'Single successful exact cohort receipt required');need(previous<=time(r.startedAtUtc)&&time(r.startedAtUtc)<=time(r.completedAtUtc)&&time(r.completedAtUtc)<=completed,'Cohort ordering/chronology differs');previous=time(r.completedAtUtc);need(r.executable===admission.runtime.nodeExecutable&&r.nodeSha256===admission.runtime.nodeSha256&&require('./backendRuntimeEvidenceAccess31.cjs').fs.realpathSync(r.cwd)===require('./backendRuntimeEvidenceAccess31.cjs').fs.realpathSync(repoRoot),'Cohort runtime or checkout differs');eq(r.arguments,['--no-global-search-paths',require('./backendRuntimeEvidenceAccess31.cjs').path.join(r.cwd,'tools/release/captureBackendRuntimePreparedInputs31.cjs'),'--config',require('./backendRuntimeEvidenceAccess31.cjs').path.join(evidenceDirectory,'deployment-attempts',approvalPointer.sha256,phase,'context.json')],'Instrumented deployment arguments differ');eq(r.cliArguments,['deploy','--only',names.map(n=>'functions:'+n).join(','),'--project','crm3-baf-ops-b8638','--non-interactive'],'Actual fixed CLI arguments differ');for(const point of [r.sourceBefore,r.sourceAfter])need(point?.commit===admission.source.commit&&point.tree===admission.source.tree&&point.functionsTree===admission.source.functionsTree&&point.branch==='main'&&point.originMain===admission.source.commit&&point.liveMain===admission.source.commit&&point.clean===true,'Command exact clean local/origin/live main binding differs');eq(r.requiredProducerBindings,admission.requiredProducerBindings,'Command producers differ');eq(r.requiredProposalBindings,admission.requiredProposalBindings,'Command executing proposal differs');fileBinding(evidenceDirectory,r.stdout);fileBinding(evidenceDirectory,r.stderr);
 const capture=object(fileBinding(evidenceDirectory,r.capture)),instrumented=object(fileBinding(evidenceDirectory,r.instrumentedCompletion));need(capture.actualCliPreparationCaptured===true&&capture.phase===phase&&instrumented.actualPreparationCaptured===true&&instrumented.phase===phase,'Actual phase preparation provenance missing');eq(capture.approvalPointer,approvalPointer,'Capture deployment approval differs');eq(capture.instrumentationProducerSha256,admission.runtime.instrumentationProducerSha256,'Actual capture producers differ');eq(instrumented.capture,r.capture,'Completion does not bind actual capture');eq(instrumented.archive,r.archive,'Completion does not bind actual ZIP');const uploaded=verifyUploadedArchiveCapture31(evidenceDirectory,r.archive,capture);uploadedArchives.push(uploaded);eq(instrumented.events.filter(e=>e.kind==='function-update').map(e=>e.name).sort(),names,'Exact once-only Function update events required');need(time(r.startedAtUtc)<=time(capture.startedAtUtc)&&time(capture.startedAtUtc)<=time(capture.completedAtUtc)&&time(capture.completedAtUtc)<=time(r.completedAtUtc),'Actual capture must follow the decision and precede cohort completion');need(time(admission.decisionAtUtc)<=time(capture.startedAtUtc),'Actual CLI capture predates deployment consent');const writes=instrumented.events.filter(e=>e.sequence);eq(instrumented.liveObservations.map(x=>x.sequence).sort((x,y)=>x-y),writes.map(x=>x.sequence).sort((x,y)=>x-y),'Every actual mutation needs its original live observation');for(const record of instrumented.liveObservations){const observed=object(fileBinding(evidenceDirectory,record.observation)),intent=object(fileBinding(evidenceDirectory,record.mutationIntent));need(intent.sequence===record.sequence&&intent.phase===phase&&intent.kind===record.kind&&time(r.startedAtUtc)<=time(observed.observedAtUtc)&&time(observed.completedAtUtc)<=time(intent.atUtc)&&time(intent.atUtc)<=time(r.completedAtUtc),'Mutation admission chronology differs');executionGate.verifyPreservedLiveGitHub31(observed,admission,decisionRecord);}const cohortControls=require('./backendRuntimeControls31.cjs').verifyCurrentCohortControls31({repoRoot,sourceCommit:admission.source.commit,evidenceDirectory,beforePointer:object(fileBinding(evidenceDirectory,admission.preflightPointers.controls)).measurementPointer,currentPointer:instrumented.currentControls,schedulerBaseline:admission.schedulerBaseline,approvalSha256:approvalPointer.sha256,decisionAtUtc:admission.decisionAtUtc,phase,cohorts:admission.cohorts,endpointRuntimeHashes:capture.endpointRuntimeHashes,requiredProducerBindings:admission.requiredProducerBindings,installedControlRuntime:admission.installedControlRuntime});verifyCohortControlChronology31(r,capture,cohortControls);actualCaptures.push(capture);
 }eq(covered.sort(),admission.cohorts.fleet,'Cohort union must be exact19 without repeats');
 const deploymentDecision=committed(authorityRoot,approvalPointer,a.PATHS.approval),proof=a.helpers.child(authorityRoot,approvalPointer.commit,deploymentDecision.runtimeProof,a.PATHS.runtime),intent=object(fileBinding(evidenceDirectory,proof.intendedHashInputs));need(time(proof.startedAtUtc)<=time(intent.startedAtUtc)&&time(intent.completedAtUtc)<=time(proof.completedAtUtc)&&time(intent.completedAtUtc)<=decision,'Approved intent must remain before the decision');const prepared=actualCaptures[0];for(const capture of actualCaptures){need(JSON.stringify(capture.environmentVariables)===JSON.stringify(intent.environmentVariables)&&admission.cohorts.fleet.every(name=>JSON.stringify(capture.endpoints[name])===JSON.stringify(intent.endpoints[name]))&&capture.sourceArchiveHash===intent.sourceArchiveHash,'Actual ordered prepared inputs differ from separately approved intent');const actual=endpointRuntimeHashes31({sourceArchiveHash:closure.sourceArchiveHash,inputs:capture,runtime:admission.runtime,names:admission.cohorts.fleet,source:admission.source});eq(capture.endpointRuntimeHashes,actual,'Actual captured labels differ from pinned recipe');eq(closure.endpointRuntimeHashes,actual,'Actual phases do not share approved endpoint identity');}const derivedLabels=endpointRuntimeHashes31({sourceArchiveHash:closure.sourceArchiveHash,inputs:prepared,runtime:admission.runtime,names:admission.cohorts.fleet,source:admission.source});
 const readbacks={};eq(Object.keys(closure.readbacks??{}).sort(),['functionFleet','iamDependencies','firestoreRulesAndIndexes'].sort(),'Every final raw readback required');
 for(const [key,pointer]of Object.entries(closure.readbacks)){const child=object(fileBinding(evidenceDirectory,pointer));require('./backendRuntimeReadbacks31.cjs').verifyMeasuredReadback31({repoRoot,candidateSource:admission.source,backendCommit:admission.source.commit,child,key,earliestUtc:closure.completedAtUtc,latestUtc:closure.recordedAtUtc,expectedRuntimeHash:derivedLabels,collectionEnvelope:key==='iamDependencies'?object(fileBinding(evidenceDirectory,closure.iamCollectionProcess)):undefined});readbacks[key]=child;}
 const rows=readbacks.iamDependencies.outputs.functions;eq(rows.map(x=>x.name).sort(),admission.cohorts.fleet,'Final IAM fleet differs');
 const manifest=closure.archiveExpectedFiles;need(manifest&&Object.keys(manifest).length>0,'Actual built-source member manifest required');for(const [name,value]of Object.entries(manifest)){need(Number.isSafeInteger(value.bytes)&&value.bytes>=0&&/^[A-F0-9]{64}$/.test(value.sha256),'Invalid archive member expectation');const raw=name.startsWith('lib/')?fileBinding(evidenceDirectory,proof.emittedFiles[name]):git(repoRoot,['show',admission.source.commit+':functions/'+name]);need(hash(raw)===value.sha256&&raw.length===value.bytes,'Archive member is not exact source/build M');}
 eq(manifest,actualArchiveInventory31({repoRoot,sourceCommit:admission.source.commit,buildRoot:proof.candidateBuildRoot,runtime:admission.runtime}),'Complete actual pinned-CLI package inventory differs');
 for(const uploaded of uploadedArchives)need(verifyArchiveBytes31(uploaded,manifest).sourceArchiveHash===closure.sourceArchiveHash,'Uploaded archive source differs from exact M/build');
 const sourceMembers=a.helpers.gtext(repoRoot,['ls-tree','-r','--name-only',admission.source.commit,'--','functions/src']).split(/\r?\n/).filter(Boolean).map(p=>p.slice('functions/'.length));need(sourceMembers.every(p=>Object.hasOwn(manifest,p)),'Archive omits current source members');eq(Object.keys(manifest).filter(p=>p.startsWith('lib/')).sort(),Object.keys(proof.emittedFiles).sort(),'Archive emitted population differs from complete actual build');
 need(manifest['package.json']?.sha256===a.PINS['functions/package.json']&&manifest['package-lock.json']?.sha256===a.PINS['functions/package-lock.json'],'Archive misses repaired exact Functions manifests');
 const archivePointers=closure.archives;eq(Object.keys(archivePointers??{}).sort(),[...new Set(rows.map(r=>r.sourceArchive.sha256))].sort(),'All distinct deployed archives required');
 for(const[digest,pointer]of Object.entries(archivePointers)){need(pointer.sha256===digest,'Archive pointer digest differs');const verified=verifyArchiveBytes31(fileBinding(evidenceDirectory,pointer),manifest);need(verified.sourceArchiveHash===closure.sourceArchiveHash,'Actual verified archive member hash differs from package source hash');}
 for(const r of rows){need(time(r.updateTime)>=start&&time(r.updateTime)<=completed&&r.sourceArchive.generationPinnedDownload===true&&/^[1-9][0-9]*$/.test(r.source.generation)&&r.source.object===r.name+'/function-source.zip','Function deployment/archive generation is not bound');need(r.dependencies.packageManifestSha256===a.PINS['functions/package.json']&&r.dependencies.packageLockSha256===a.PINS['functions/package-lock.json'],'Deployed archive dependencies differ');}
 bindPreparedHashInputsToControls31({inputs:prepared,raw:object(fileBinding(evidenceDirectory,closure.controlsAfter)),names:admission.cohorts.fleet,expectedHashes:derivedLabels});
 const beforeEnvelope=object(fileBinding(evidenceDirectory,admission.preflightPointers.controls));const controls=require('./backendRuntimeControls31.cjs').verifyPreservedControls31({repoRoot,sourceCommit:admission.source.commit,evidenceDirectory,beforePointer:beforeEnvelope.measurementPointer,afterPointer:closure.controlsAfter,approvalSha256:approvalPointer.sha256,decisionAtUtc:admission.decisionAtUtc,completedAtUtc:closure.completedAtUtc,requiredProducerBindings:admission.requiredProducerBindings,installedControlRuntime:admission.installedControlRuntime});
 return {ok:true,proposalOnly:true,deploymentAuthorized:false,constructionAuthority:false,source:admission.source,approvalPointer,closurePointer,completedAtUtc:closure.completedAtUtc,recordedAtUtc:closure.recordedAtUtc,readbacks,controls};
}
function verifyBackendRuntimeClosure31(config){return require('./backendRuntimeEvidenceAccess31.cjs').runEvidence31(config,()=>verifyBackendRuntimeClosure31Inner(config));}
module.exports={verifyUploadedArchiveCapture31,verifyCohortControlChronology31,actualArchiveInventory31,verifyArchiveBytes31,verifyBackendRuntimeClosure31,endpointRuntimeHashes31,bindPreparedHashInputsToControls31,crc32};
