'use strict';
// Local sentinel fixtures prove refusal occurs before unbound module evaluation.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process');
const a=require('./backendRuntimeAdmission31.cjs'),controls=require('./backendRuntimeControls31.cjs'),closure=require('./backendRuntimeClosure31.cjs');
const access=require('./backendRuntimeEvidenceAccess31.cjs');
const readbacks=require('./backendRuntimeReadbacks31.cjs');
function relocatedControlsFixture(){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'crm31-cache-')),bundle=path.join(root,'bundle'),runtime=path.join(bundle,'runtime'),original=path.join(root,'original-unavailable'),bindings={},members=[];
 const files={
  'functions/node_modules/typescript/package.json':'{"name":"typescript","main":"lib/typescript.js"}',
  'functions/node_modules/typescript/lib/typescript.js':'module.exports={};',
  'functions/node_modules/firebase-functions/package.json':'{"name":"firebase-functions"}',
  'functions/node_modules/firebase-functions/lib/runtime/manifest.js':'module.exports={};',
 };
 for(const[file,text]of Object.entries(files)){const dest=path.join(runtime,file),raw=Buffer.from(text);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,raw);bindings[file]=a.helpers.hash(raw);members.push({path:'runtime/'+file,bytes:raw.length,sha256:bindings[file]});}
 const outer=path.join(root,'outer.cjs');fs.writeFileSync(outer,'module.exports=31;');
 const run=(action,verifierFiles={})=>access.runRelocated31({privateBundleRoot:bundle,relocation:{schemaVersion:1,roots:[{original,memberRoot:'runtime'}],files:[]},members,verifierFiles},action);
 return {root,bundle,runtime,original,bindings,members,outer,run};
}
test('relocated controls ignore unrelated cached caller without evaluating it as evidence',()=>{const x=relocatedControlsFixture();assert.equal(require(x.outer),31);assert.doesNotThrow(()=>x.run(()=>controls.verifyInstalledControlsRuntime(x.runtime,x.bindings)));});
test('relocated load guard leaves unrelated caller imports outside installed runtime scope',()=>{const x=relocatedControlsFixture();assert.equal(x.run(()=>controls.withInstalledControlsRuntime31(x.runtime,x.bindings,()=>require(x.outer))),31);});
test('relocated cache still rejects an unbound measured dependency',()=>{const x=relocatedControlsFixture(),file=path.join(x.runtime,'functions/node_modules/unbound.cjs');fs.writeFileSync(file,'module.exports=1;');require(file);try{assert.throws(()=>x.run(()=>controls.verifyInstalledControlsRuntime(x.runtime,x.bindings)),/Unbound loaded controls dependency/);}finally{delete require.cache[file];}});
test('relocated cache still rejects substituted admitted replay helper bytes',()=>{const x=relocatedControlsFixture(),sha=a.helpers.hash(fs.readFileSync(x.outer));require(x.outer);fs.appendFileSync(x.outer,'// substituted');assert.throws(()=>x.run(()=>controls.verifyInstalledControlsRuntime(x.runtime,x.bindings),{[x.outer]:sha}),/Source-bound replay producer changed/);});
test('relocated loader rejects substituted admitted replay helper before evaluation',()=>{const x=relocatedControlsFixture(),sha=a.helpers.hash(fs.readFileSync(x.outer));fs.appendFileSync(x.outer,'// substituted');assert.throws(()=>x.run(()=>controls.withInstalledControlsRuntime31(x.runtime,x.bindings,()=>require(x.outer)),{[x.outer]:sha}),/Source-bound replay producer changed/);assert.equal(require.cache[x.outer],undefined);});
test('an installed alias resolving outside the measured runtime is refused before evaluation',()=>{const x=relocatedControlsFixture(),outside=path.join(x.root,'outside'),alias=path.join(x.runtime,'functions/node_modules/alias'),marker=path.join(x.root,'alias-executed');fs.mkdirSync(outside);fs.writeFileSync(path.join(outside,'index.js'),"require('node:fs').writeFileSync("+JSON.stringify(marker)+",'unsafe');");fs.symlinkSync(outside,alias,process.platform==='win32'?'junction':'dir');assert.throws(()=>controls.withInstalledControlsRuntime31(x.runtime,x.bindings,()=>require(alias)),/Installed controls dependency escaped/);assert.equal(fs.existsSync(marker),false);});
test('direct controls runtime resolution maps an unavailable original root',()=>{const x=relocatedControlsFixture();assert.equal(fs.existsSync(x.original),false);assert.doesNotThrow(()=>x.run(()=>controls.verifyInstalledControlsRuntime(x.original,x.bindings)));});
function nativeContextFixture(){
 const x=relocatedControlsFixture(),sourceFiles={
  'release/function-fleet-runtime-identity-policy.json':'{}',
  'tools/release/scopedCallableInvokerIam.js':'module.exports={};',
  'tools/release/collectProductionGlobalPullBackend.js':'module.exports={mappedSource:true};',
  'native-marker.txt':'mapped native context',
  'tools/release/reviewedBackendControls.js':"exports.sourceOptions=(root,commit)=>{const path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');assert.equal(root,"+JSON.stringify(x.runtime)+");require(path.join(root,'functions/node_modules/typescript'));require(path.join(root,'functions/node_modules/firebase-functions/lib/runtime/manifest.js'));assert.equal(fs.readFileSync(path.join(root,'native-marker.txt'),'utf8'),'mapped native context');assert.equal(require('node:child_process').execFileSync('git',['--no-replace-objects','-C',root,'show',commit+':native-marker.txt'],{encoding:'utf8',windowsHide:true}),'mapped native context');throw Error('mapped native controls boundary reached');};",
 };
 const put=(file,text)=>{const raw=Buffer.from(text),dest=path.join(x.runtime,file);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,raw);x.members.push({path:'runtime/'+file,bytes:raw.length,sha256:a.helpers.hash(raw)});return {file,sha256:a.helpers.hash(raw)};};
 const requiredProducerBindings={};for(const[file,text]of Object.entries(sourceFiles)){const p=put(file,text);if(file.startsWith('tools/'))requiredProducerBindings[file]=p.sha256;}
 const git=(...args)=>cp.execFileSync('git',['-c','user.name=Synthetic boundary fixture','-c','user.email=fixture@invalid.example','-c','core.autocrlf=false','-C',x.runtime,...args],{encoding:'utf8',windowsHide:true}).trim();git('init');git('add','--','release','tools','native-marker.txt');git('commit','-m','Synthetic native boundary source');
 const sourceCommit=git('rev-parse','HEAD'),pointer=put('evidence.json','{}');
 return {...x,sourceCommit,requiredProducerBindings,input:{repoRoot:x.original,sourceCommit,evidenceDirectory:x.original,beforePointer:pointer,currentPointer:pointer,afterPointer:pointer,schedulerBaseline:pointer,phase:'callables',requiredProducerBindings,installedControlRuntime:x.bindings}};
}
for(const entry of ['verifyPreservedControlsBefore31','verifyCurrentCohortControls31','verifyPreservedControls31'])test(entry+' maps native producer inputs without rewriting original evidence identity',()=>{const x=nativeContextFixture(),before=JSON.stringify(x.input);assert.equal(fs.existsSync(x.original),false);assert.throws(()=>x.run(()=>controls[entry](x.input)),/mapped native controls boundary reached/);assert.equal(JSON.stringify(x.input),before);});
test('readback source import uses mapped bytes when the original repository is unavailable',()=>{const x=nativeContextFixture();assert.equal(fs.existsSync(x.original),false);assert.deepEqual(x.run(()=>readbacks.load(x.original,x.sourceCommit,'tools/release/collectProductionGlobalPullBackend.js')),{mappedSource:true});});
test('mapped readback source substitution is refused before native import',()=>{const x=nativeContextFixture(),file=path.join(x.runtime,'tools/release/collectProductionGlobalPullBackend.js');fs.appendFileSync(file,'// substituted');assert.throws(()=>x.run(()=>readbacks.load(x.original,x.sourceCommit,'tools/release/collectProductionGlobalPullBackend.js')),/Relocated evidence changed|Loaded producer differs/);assert.equal(require.cache[file],undefined);});
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'crm31-load-')),pkg=path.join(root,'functions/node_modules/example');fs.mkdirSync(pkg,{recursive:true});const marker=path.join(root,'executed'),entry=path.join(pkg,'index.cjs'),leaf=path.join(pkg,'leaf.cjs');fs.writeFileSync(entry,"module.exports=require('./leaf.cjs');\n");fs.writeFileSync(leaf,"require('node:fs').writeFileSync("+JSON.stringify(marker)+",'unsafe');module.exports=1;\n");const binding=file=>a.helpers.hash(fs.readFileSync(file));return {root,pkg,marker,entry,leaf,binding};}
for(const kind of ['omitted','changed','escaped'])test('controls dependency '+kind+' is refused before its sentinel evaluates',()=>{const x=fixture(),bindings={'functions/node_modules/example/index.cjs':x.binding(x.entry)};if(kind==='changed'){bindings['functions/node_modules/example/leaf.cjs']=x.binding(x.leaf);fs.appendFileSync(x.leaf,'// changed bytes\n');}if(kind==='escaped'){const outside=path.join(x.root,'functions/outside.cjs');fs.copyFileSync(x.leaf,outside);fs.writeFileSync(x.entry,"module.exports=require('../../outside.cjs');\n");bindings['functions/node_modules/example/index.cjs']=x.binding(x.entry);}assert.throws(()=>controls.withInstalledControlsRuntime31(x.root,bindings,()=>require(x.entry)),/Unbound installed|escaped/);assert.equal(fs.existsSync(x.marker),false);});
test('fully measured local controls dependency can evaluate',()=>{const x=fixture(),bindings={'functions/node_modules/example/index.cjs':x.binding(x.entry),'functions/node_modules/example/leaf.cjs':x.binding(x.leaf)};assert.equal(controls.withInstalledControlsRuntime31(x.root,bindings,()=>require(x.entry)),1);assert.equal(fs.readFileSync(x.marker,'utf8'),'unsafe');});
for(const kind of ['omitted','changed'])test('archive child refuses '+kind+' transitive bytes before sentinel evaluation',()=>{const x=fixture(),lib=path.join(x.root,'tooling/firebase-cli/node_modules/firebase-tools/lib'),entrypoint=path.join(lib,'bin/firebase.js');fs.mkdirSync(path.dirname(entrypoint),{recursive:true});fs.mkdirSync(path.join(lib,'deploy/functions'),{recursive:true});fs.writeFileSync(entrypoint,'');const enumerator=path.join(lib,'fsAsync.js'),prepare=path.join(lib,'deploy/functions/prepareFunctionsUpload.js'),leaf=path.join(lib,'leaf.cjs');fs.writeFileSync(enumerator,"require('./leaf.cjs');exports.readdirRecursive=async()=>[];\n");fs.writeFileSync(prepare,'');fs.copyFileSync(x.leaf,leaf);const map={'firebase-tools/lib/fsAsync.js':x.binding(enumerator)};if(kind==='changed'){map['firebase-tools/lib/leaf.cjs']=x.binding(leaf);fs.appendFileSync(leaf,'// changed bytes\n');}const mapFile=path.join(x.root,'cli-files.json');fs.writeFileSync(mapFile,JSON.stringify(map));fs.writeFileSync(path.join(x.root,'firebase.json'),JSON.stringify({functions:[{source:'functions',codebase:'default',ignore:[]}]}));const git=(...args)=>cp.execFileSync('git',['-c','user.name=Local fixture','-c','user.email=fixture@invalid.example','-C',x.root,...args],{encoding:'utf8',windowsHide:true}).trim();git('init');git('add','firebase.json');git('commit','-m','Synthetic packaging source');const runtime={nodeExecutable:process.execPath,cliEntrypoint:entrypoint,cliFileBindings:{path:mapFile,sha256:x.binding(mapFile)},packagingProducerSha256:{enumerator:x.binding(enumerator),prepare:x.binding(prepare)}};assert.throws(()=>closure.actualArchiveInventory31({repoRoot:x.root,sourceCommit:git('rev-parse','HEAD'),buildRoot:x.root,runtime}),/Unbound CLI dependency before evaluation/);assert.equal(fs.existsSync(x.marker),false);});

test('a consistently substituted command/completion ZIP pointer cannot replace captured upload bytes',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'crm31-upload-')),original=Buffer.from('captured original upload'),other=Buffer.from('different ZIP substitution'),capture={archiveSha256:a.helpers.hash(original),archiveBytes:original.length};fs.writeFileSync(path.join(root,'original.zip'),original);fs.writeFileSync(path.join(root,'other.zip'),other);const originalPointer={file:'original.zip',sha256:a.helpers.hash(original)},substitute={file:'other.zip',sha256:a.helpers.hash(other)},command={archive:substitute},completion={archive:substitute};assert.deepEqual(command.archive,completion.archive);assert.deepEqual(closure.verifyUploadedArchiveCapture31(root,originalPointer,capture),original);assert.throws(()=>closure.verifyUploadedArchiveCapture31(root,command.archive,capture),/Retained uploaded ZIP differs/);});
test('current controls must begin inside the actual cohort interval',()=>{const command={startedAtUtc:'2026-10-01T20:01:00Z'},capture={completedAtUtc:'2026-10-01T20:03:00Z'},controls={startedAtUtc:'2026-10-01T20:01:01Z',completedAtUtc:'2026-10-01T20:02:00Z'};assert.doesNotThrow(()=>closure.verifyCohortControlChronology31(command,capture,controls));assert.throws(()=>closure.verifyCohortControlChronology31(command,capture,{...controls,startedAtUtc:'2026-10-01T20:00:59Z'}),/Fresh cohort controls/);});
