'use strict';
// PRIVATE PROPOSAL. No command here deploys, grants approval, or writes authority.
const fs=require('./backendRuntimeEvidenceAccess31.cjs').fs,path=require('./backendRuntimeEvidenceAccess31.cjs').path,crypto=require('node:crypto');
const {execFileSync}=require('node:child_process');
const {isDeepStrictEqual}=require('node:util');
const BASELINE='2aa30de56cfdb960da3eeefd8956d8cbbae57b46';
const PROJECT='crm3-baf-ops-b8638',REGION='asia-south1',REPO='abhishekvatsa/crm3_baf_ops';
const PROFILE='build31-exact-grpc-runtime-backend-v1';
const PATHS=Object.freeze({approval:'release/approvals/build31-runtime-backend-deployment-approval.json',owner:'release/approvals/build31-runtime-backend-owner-authorization.json',release:'release/evidence/build31-runtime-backend-main-ci.json',security:'release/evidence/build31-runtime-backend-main-security.json',runtime:'release/evidence/build31-runtime-backend-local-proof.json',closure:'release/evidence/build31-runtime-backend-deployment-closure.json',client:'release/approvals/build31-runtime-client-compatibility-approval.json'});
const PINS=Object.freeze({'functions/package.json':'D7336A00B061CA4D212947FD114E6B405607D50FFF2A9B0EA6AE33869AF2FE97','functions/package-lock.json':'00CE45072D8F1A59CFB6426AFB2373908CB0809F6BDA7F04DB6979913217043F','tooling/firebase-cli/package.json':'E07F714D44D80D5EC0C09E7FDE07A2AE0CFC5497184B27DF16EB59CEF15A3786','tooling/firebase-cli/package-lock.json':'97361DFBE82BBD8B5B22240584EE5AC60EE5A628556849C779EEBBF2745335E1'});
const RELEASE_JOBS=['Flutter host analysis + tests + no-loss contracts','Android release package + cold-start proof (non-production)','Android emulator shell + business integration (not physical-device evidence)','Firestore Rules + governed callable emulator','Cloud Functions host build + non-emulator tests'].sort();
const SECURITY_JOBS=['CodeQL (actions)','CodeQL (java-kotlin)','CodeQL (javascript-typescript)','CodeQL (python)'].sort();
const PROPOSAL_FILES=['backendRuntimeExecutionAdmission31.cjs','executeBackendRuntime31.cjs','captureBackendRuntimePreparedInputs31.cjs','runtimeDeploymentTransportGuard31.cjs','backendRuntimeClosedReplay31.cjs','backendRuntimeEvidenceAccess31.cjs','backendRuntimeAdmission31.cjs','backendRuntimeProof31.cjs','backendRuntimeReadbacks31.cjs','backendRuntimeClosure31.cjs','backendRuntimeControls31.cjs','backendRuntimeExecution31.cjs','closure-preflight31.cjs','clientRuntimeCompatibility31.cjs'];
const SCOPE=Object.freeze({buildNumber:31,backendDeployment:true,functionsOnly:true,grpcRuntimeChanged:true,businessLogicChanged:false,firestoreRulesDeployment:false,firestoreIndexesDeployment:false,iamMutation:false,enforcementMutation:false,manualSchedulerExecution:false,clientConstruction:false,distribution:false});
const PROTECTED=['functions','firebase.json','.firebaserc','firestore.rules','firestore.indexes.json','android','release/function-fleet-runtime-identity-policy.json','release/lr03-lr06-functions-live-readback-policy.json'];
function need(v,m){if(!v)throw new Error(m);}
function eq(a,b,m){need(isDeepStrictEqual(a,b),m);}
function hash(b){return crypto.createHash('sha256').update(b).digest('hex').toUpperCase();}
function hex(v,n){return typeof v==='string'&&new RegExp('^[0-9a-f]{'+n+'}$','i').test(v);}
function time(v){need(typeof v==='string'&&/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d{1,9})?Z$/.test(v),'Explicit UTC instant required');const [base,fraction='']=v.slice(0,-1).split('.');const ms=Date.parse(base+'Z');need(Number.isFinite(ms)&&new Date(ms).toISOString().slice(0,19)===base&&base.slice(0,4)!=='0000','Invalid calendar instant');return BigInt(ms)*1000000n+BigInt((fraction+'000000000').slice(0,9));}
function git(root,args){
 const actual=require('./backendRuntimeEvidenceAccess31.cjs').resolveOriginal(root),nativeFs=require('node:fs'),nativePath=require('node:path');
 const gitDir=nativePath.join(actual,'.git');need(nativeFs.lstatSync(gitDir).isDirectory()&&!nativeFs.lstatSync(gitDir).isSymbolicLink(),'Replay requires a real self-contained Git directory');for(const name of ['commondir','gitdir','objects/info/alternates','info/grafts'])need(!nativeFs.existsSync(nativePath.join(gitDir,name))||!require('./backendRuntimeEvidenceAccess31.cjs').current()?.relocation,'Bundled Git cannot redirect to external state');
 const config=nativePath.join(actual,'.git','config');if(nativeFs.existsSync(config)){const raw=nativeFs.readFileSync(config,'utf8');need(!/^\s*\[\s*(?:include(?:If)?|filter|diff)\b/im.test(raw)&&!/^\s*worktree\s*=/im.test(raw),'Executable or external Git configuration is not admitted');}
 const env=Object.fromEntries(Object.entries(process.env).filter(([key])=>!/^GIT_/i.test(key)));Object.assign(env,{GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:process.platform==='win32'?'NUL':'/dev/null',GIT_TERMINAL_PROMPT:'0',GIT_PAGER:'cat',GIT_OPTIONAL_LOCKS:'0'});
 return execFileSync('git',['--no-replace-objects','--no-pager','-c','core.longpaths=true','-c','core.fsmonitor=false','-c','core.hooksPath='+nativePath.join(actual,'.git','crm31-disabled-hooks'),'--no-optional-locks','-c','core.untrackedCache=false','-c','core.preloadIndex=false','-c','diff.external=','-c','credential.helper=','-c','protocol.allow=never','-C',actual,...args],{env,windowsHide:true,stdio:['ignore','pipe','pipe']});
}
function gtext(root,args){return git(root,args).toString('utf8').trim();}
function safeRel(p){need(typeof p==='string'&&!p.includes('\\')&&!p.includes(':')&&!p.startsWith('/')&&p.split('/').every(x=>x&&x!=='.'&&x!=='..'),'Unsafe relative evidence path');return p;}
function local(root,p){safeRel(p);const real=fs.realpathSync(path.resolve(root,p)),rel=path.relative(fs.realpathSync(root),real);need(rel&&!rel.startsWith('..')&&!path.isAbsolute(rel),'Evidence escapes root');return fs.readFileSync(real);}
function object(bytes){const value=JSON.parse(bytes.toString('utf8'));need(value!==null&&typeof value==='object'&&!Array.isArray(value),'JSON object required');return value;}
function committed(root,pointer,fixedFile){need(hex(pointer?.commit,40)&&hex(pointer?.sha256,64)&&pointer.file===fixedFile,'Exact immutable pointer required: '+fixedFile);const raw=git(root,['show',pointer.commit+':'+safeRel(pointer.file)]);need(hash(raw)===pointer.sha256.toUpperCase(),'Committed evidence digest mismatch');return require('./backendRuntimeEvidenceAccess31.cjs').resolveAuthorityRecord31(object(raw));}
function child(root,custody,pointer,fixedFile){return committed(root,{...pointer,commit:custody},fixedFile);}
function source(root,commit){need(hex(commit,40),'Exact source commit required');return {commit,tree:gtext(root,['rev-parse',commit+'^{tree}']),functionsTree:gtext(root,['rev-parse',commit+':functions'])};}
function ancestor(root,a,b){git(root,['merge-base','--is-ancestor',a,b]);}
function inventory(root,commit,paths){const out={};for(const line of git(root,['ls-tree','-r','-z',commit,'--',...paths]).toString('utf8').split('\0').filter(Boolean)){const [meta,file]=line.split('\t');const [mode,type,oid]=meta.split(' ');need(type==='blob'&&['100644','100755'].includes(mode),'Protected files must be regular files');out[file]=mode+':'+oid;}return out;}
function measureSource31(repoRoot,commit){
 const root=fs.realpathSync(repoRoot),s=source(root,commit);ancestor(root,BASELINE,commit);
 const before=inventory(root,BASELINE,PROTECTED),after=inventory(root,commit,PROTECTED);eq(Object.keys(after).sort(),Object.keys(before).sort(),'Protected file inventory changed');
 for(const file of Object.keys(before))if(!['functions/package.json','functions/package-lock.json'].includes(file))need(after[file]===before[file],'Protected source changed: '+file);
 for(const[file,digest]of Object.entries(PINS))need(hash(git(root,['show',commit+':'+file]))===digest,'Outside frozen reviewed dependency delta: '+file);
 const policy=object(git(root,['show',commit+':release/function-fleet-runtime-identity-policy.json']));need(policy.productionProjectId===PROJECT,'Wrong fleet project');
 const cohorts={callables:[],events:[],schedulers:[],fleet:Object.keys(policy.functionBindings).sort()};
 for(const[name,b]of Object.entries(policy.functionBindings)){need(/^[A-Za-z][A-Za-z0-9_]*$/.test(name),'Unsafe Function name');if(b.workloadClass.includes('CALLABLE'))cohorts.callables.push(name);else if(['FIRESTORE_NOTIFICATION_TRIGGER','FIRESTORE_PROTOCOL_TRIGGER'].includes(b.workloadClass))cohorts.events.push(name);else if(b.workloadClass==='SCHEDULED_FIRESTORE_MUTATION')cohorts.schedulers.push(name);else need(false,'Unknown Function class');}
 for(const v of Object.values(cohorts))v.sort();eq([cohorts.callables.length,cohorts.events.length,cohorts.schedulers.length,cohorts.fleet.length],[13,5,1,19],'Existing exact 19 Function fleet required');
 const policySource=object(git(root,['show',commit+':release/production-release-policy.json']));need([30,31].includes(policySource.versionPolicy?.buildNumber),'Source must be predecessor30 or candidate31 generation');
 return {source:s,cohorts,protectedCount:Object.keys(after).length,pins:PINS};
}
function verifyCi31(ci,sourceValue,kind,decisionAtUtc){
 const expected=kind==='release'?RELEASE_JOBS:SECURITY_JOBS,workflow=kind==='release'?'.github/workflows/release-gate.yml':'.github/workflows/codeql.yml',type=kind==='release'?'github-exact-main-release-gate':'github-exact-main-codeql';
 const {run,jobs,pullRequest:pr}=ci;need(ci.schemaVersion===1&&ci.evidenceType===type&&ci.repository===REPO&&ci.sourceCommit===sourceValue.commit&&ci.sourceTree===sourceValue.tree,'CI source/schema differs');
 need(Number.isSafeInteger(pr?.number)&&pr.number>0&&pr.merged===true&&pr.merge_commit_sha===sourceValue.commit&&pr.base?.ref==='main'&&pr.base.repo?.full_name===REPO,'Exact normal merged PR required');
 need(Number.isSafeInteger(run?.id)&&run.id>0&&Number.isSafeInteger(run.run_attempt)&&run.run_attempt>0&&run.repository?.full_name===REPO&&run.head_sha===sourceValue.commit&&run.head_branch==='main'&&run.event==='push'&&run.path===workflow&&run.status==='completed'&&run.conclusion==='success','Exact successful main workflow required');
 const merged=time(pr.merged_at),started=time(run.created_at),completed=time(run.updated_at),captured=time(ci.capturedAtUtc),decision=time(decisionAtUtc);need(merged<=started&&started<=completed&&completed<=captured&&captured<=decision,'CI chronology differs');
 need(jobs?.total_count===expected.length&&Array.isArray(jobs.jobs)&&jobs.jobs.length===expected.length,'Complete CI population required');eq(jobs.jobs.map(x=>x.name).sort(),expected,'Required CI jobs differ');need(new Set(jobs.jobs.map(x=>x.id)).size===expected.length,'CI job IDs repeat');
 for(const j of jobs.jobs)need(Number.isSafeInteger(j.id)&&j.id>0&&j.run_id===run.id&&j.run_attempt===run.run_attempt&&j.head_sha===sourceValue.commit&&j.status==='completed'&&j.conclusion==='success'&&started<=time(j.completed_at)&&time(j.completed_at)<=completed,'CI job failed or source/time differs');
 return {runId:run.id,completedAtUtc:run.updated_at,pullRequestNumber:pr.number};
}
function verifyCustodyDelta(root,sourceCommit,custody){ancestor(root,sourceCommit,custody);const changes=gtext(root,['diff','--name-only',sourceCommit,custody]).split(/\r?\n/).filter(Boolean);need(changes.length>0&&changes.every(p=>/^release\/(approvals|evidence)\/build31-runtime-[A-Za-z0-9_-]+\.json$/.test(p)),'Custody commit may add only fixed Build31 runtime records');}
function fileBinding(root,pointer){need(hex(pointer?.sha256,64),'File SHA256 required');const raw=local(root,pointer.file);need(hash(raw)===pointer.sha256.toUpperCase(),'Private file binding differs: '+pointer.file);return raw;}
function verifyGithubObserverRuntime31(runtime){
 need(typeof runtime?.githubExecutable==='string'&&path.isAbsolute(runtime.githubExecutable)&&hex(runtime.githubExecutableSha256,64),'GitHub observer binary binding required');
 need(hash(fs.readFileSync(fs.realpathSync(runtime.githubExecutable)))===runtime.githubExecutableSha256.toUpperCase(),'GitHub observer binary bytes differ');
 return {executable:runtime.githubExecutable,sha256:runtime.githubExecutableSha256.toUpperCase()};
}
function verifyRuntimeFiles(runtime){
 verifyGithubObserverRuntime31(runtime);
 need(runtime?.nodeVersion==='22.15.0'&&runtime.firebaseCliVersion==='15.22.4'&&runtime.lockSha256===PINS['tooling/firebase-cli/package-lock.json'],'Fixed Node22/CLI/lock required');
 for(const[fileKey,hashKey]of [['nodeExecutable','nodeSha256'],['npmCliFile','npmCliSha256'],['cliEntrypoint','cliEntrypointSha256'],['fabricatorFile','fabricatorSha256'],['runApiFile','runApiSha256']]){need(typeof runtime[fileKey]==='string'&&path.isAbsolute(runtime[fileKey])&&hex(runtime[hashKey],64),'Runtime file binding required');need(hash(fs.readFileSync(fs.realpathSync(runtime[fileKey])))===runtime[hashKey].toUpperCase(),'Installed runtime differs: '+fileKey);}
 const pointer=runtime.cliFileBindings;need(pointer&&path.isAbsolute(pointer.path)&&hex(pointer.sha256,64),'Complete installed CLI file proof required');const raw=fs.readFileSync(pointer.path);need(hash(raw)===pointer.sha256,'CLI file proof differs');const bindings=object(raw),prefix=path.dirname(path.dirname(path.dirname(path.dirname(runtime.cliEntrypoint)))),files=[];function walk(dir){for(const row of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,row.name);need(!row.isSymbolicLink(),'Installed CLI proof requires regular files');if(row.isDirectory())walk(file);else{need(row.isFile(),'Installed CLI member kind differs');const rel=path.relative(prefix,file).split(path.sep).join('/');files.push(rel);need(hex(bindings[rel],64)&&hash(fs.readFileSync(file))===bindings[rel],'Installed CLI member is unbound or changed: '+rel);}}}walk(prefix);eq(files.sort(),Object.keys(bindings).sort(),'Complete installed CLI population differs');
 return runtime;
}
function verifyProducerBindings(root,commit,bindings){
 const required=['tools/release/collectFunctionFleetRuntimeIdentityReadback.js','tools/release/collectFunctionsIamDependenciesReadback.js','tools/release/collectFirestoreRulesIndexesReadback.js','tools/release/reviewedBackendControls.js','tools/release/collectProductionGlobalPullBackend.js','tools/release/scopedCallableInvokerIam.js','tools/release/deploymentFleetContract.js'];
 need(bindings&&typeof bindings==='object','Producer bindings required');eq(Object.keys(bindings).sort(),required.sort(),'Exact executing producer population required');for(const p of required)need(hex(bindings[p],64)&&hash(git(root,['show',commit+':'+p]))===bindings[p].toUpperCase()&&hash(local(root,p))===bindings[p].toUpperCase(),'Producer source/loaded bytes differ');
 return bindings;
}
function verifyProposalBindings(root,commit,bindings){eq(Object.keys(bindings??{}).sort(),PROPOSAL_FILES.map(p=>'tools/release/'+p).sort(),'Exact proposal producer population required');for(const name of PROPOSAL_FILES){const rel='tools/release/'+name;need(hex(bindings[rel],64)&&hash(git(root,['show',commit+':'+rel]))===bindings[rel]&&hash(fs.readFileSync(path.join(__dirname,name)))===bindings[rel],'Executing proposal differs from committed M: '+name);}return bindings;}
function aBaselineClosure(commit){return commit+':release/evidence/build30-current-source-backend-deployment-closure.json';}
function verifyBackendRuntimeAdmission31Inner({repoRoot,authorityRoot,approvalPointer,evidenceDirectory,nowUtc=new Date().toISOString(),requireExecutionHead=true}){
 const root=fs.realpathSync(repoRoot),authority=fs.realpathSync(authorityRoot),approval=committed(authority,approvalPointer,PATHS.approval),now=time(nowUtc);
 need(root===fs.realpathSync(gtext(root,['rev-parse','--show-toplevel']))&&authority===fs.realpathSync(gtext(authority,['rev-parse','--show-toplevel']))&&root!==authority,'Distinct actual Git top-level roots required');
 need(approval.schemaVersion===2&&approval.documentType==='build31-runtime-backend-deployment-decision'&&approval.profile===PROFILE&&approval.approved===true&&approval.projectId===PROJECT&&approval.region===REGION,'Distinct exact Build31 deployment decision required');eq(approval.scope,SCOPE,'Deployment scope differs');
 const measured=measureSource31(root,approval.source?.commit);eq(approval.source,measured.source,'Source tree/Functions object differs');eq(source(authority,measured.source.commit),measured.source,'Authority and execution Git objects differ');verifyCustodyDelta(authority,measured.source.commit,approvalPointer.commit);
 const requiredProposalBindings=verifyProposalBindings(root,measured.source.commit,approval.requiredProposalBindings);
 const decision=time(approval.decidedAtUtc),recorded=time(approval.recordedAtUtc),committedAt=BigInt(gtext(authority,['show','-s','--format=%ct',approvalPointer.commit]))*1000000000n;need(decision<=recorded&&recorded<committedAt+1000000000n&&committedAt<=now,'Approval recording/custody chronology differs');
 const owner=child(authority,approvalPointer.commit,approval.ownerAuthorization,PATHS.owner);need(owner.documentType==='build31-exact-source-runtime-backend-owner-authorization'&&owner.schemaVersion===2&&owner.approved===true&&owner.projectId===PROJECT&&owner.region===REGION,'Separate actual backend owner authorization required');eq(owner.source,measured.source,'Owner source differs');eq(owner.scope,SCOPE,'Owner scope differs');need(typeof owner.ownerInstruction==='string'&&owner.ownerInstruction.trim().length>0&&!/^(yes[—\s-]*)?prepare and test the scoped path[.!]?$/i.test(owner.ownerInstruction.trim()),'Preparation permission is not deployment authorization');need(typeof owner.ownerReference==='string'&&owner.ownerReference.trim()&&owner.ownerReference===approval.ownerReference,'Actual owner reference required');need(time(owner.authorizedAtUtc)<=time(owner.recordedAtUtc)&&time(owner.recordedAtUtc)<=decision,'Owner chronology differs');
 const releaseCi=child(authority,approvalPointer.commit,approval.mainCi,PATHS.release),securityCi=child(authority,approvalPointer.commit,approval.securityCi,PATHS.security);
 const release=verifyCi31(releaseCi,measured.source,'release',approval.decidedAtUtc),security=verifyCi31(securityCi,measured.source,'security',approval.decidedAtUtc);need(release.pullRequestNumber===security.pullRequestNumber,'CI PR binding differs');const lastCi=[release.completedAtUtc,security.completedAtUtc].sort((a,b)=>time(a)<time(b)?-1:1).at(-1);
 const parents=gtext(root,['rev-list','--parents','-n','1',measured.source.commit]).split(' ');need(parents.length===3&&[releaseCi,securityCi].every(ci=>ci.pullRequest.head?.sha===parents[2]),'Normal two-parent merge and actual PR ancestry required');
 need(time(owner.authorizedAtUtc)>=time(lastCi),'Exact owner decision must follow both main checks');
 const start=time(approval.executionWindow?.notBeforeUtc),end=time(approval.executionWindow?.notAfterUtc);need(decision<=start&&start<end&&end-start<=6n*3600n*1000000000n,'Bounded deployment window required');if(requireExecutionHead)need(start<=now&&now<=end,'Deployment decision expired or not active');
 need(typeof evidenceDirectory==='string'&&path.isAbsolute(evidenceDirectory),'Absolute private evidence directory required');const evidence=fs.realpathSync(evidenceDirectory);need(fs.statSync(evidence).isDirectory(),'Private evidence directory missing');
 const proof=child(authority,approvalPointer.commit,approval.runtimeProof,PATHS.runtime);need(proof.schemaVersion===2&&proof.documentType==='build31-runtime-backend-local-proof'&&proof.sourceCommit===measured.source.commit&&proof.functionsTree===measured.source.functionsTree,'Fresh exact-source runtime proof required');need(time(lastCi)<=time(proof.startedAtUtc)&&time(proof.startedAtUtc)<=time(proof.completedAtUtc)&&time(proof.completedAtUtc)<=decision,'Runtime collection must follow both main CI jobs');eq(proof.manifestSha256,PINS['functions/package.json'],'Runtime manifest binding differs');eq(proof.lockSha256,PINS['functions/package-lock.json'],'Runtime lock binding differs');
 const populations=['root-full','root-runtime','functions-full','functions-runtime','cli-full'];eq(Object.keys(proof.audits??{}).sort(),populations.sort(),'Every strict audit population required');for(const name of populations){const audit=object(fileBinding(evidence,proof.audits[name]));need(audit.auditReportVersion===2&&!Object.hasOwn(audit,'error')&&Object.keys(audit.vulnerabilities??{missing:true}).length===0,'Audit report is not clean');for(const k of ['info','low','moderate','high','critical','total'])need(audit.metadata?.vulnerabilities?.[k]===0,'Audit count must be numeric zero');}
 need(proof.emittedFiles&&Object.keys(proof.emittedFiles).length>0&&proof.installedDependencies,'Actual emitted/runtime evidence required');for(const p of Object.values(proof.emittedFiles))fileBinding(evidence,p);const installed=object(fileBinding(evidence,proof.installedDependencies));need(installed.problems===undefined&&installed.name==='crm3-baf-ops-functions'&&installed.dependencies,'Original installed npm runtime graph required');
 const requiredProducerBindings=verifyProducerBindings(root,measured.source.commit,approval.requiredProducerBindings);
 const runtime=verifyRuntimeFiles(approval.runtime);
 const runtimeProof=require('./backendRuntimeProof31.cjs').verifyRuntimeProofContents31({repoRoot:root,sourceCommit:measured.source.commit,evidenceDirectory:evidence,proof,runtime});
 const preflightPointers=approval.preflightPointers;eq(Object.keys(preflightPointers??{}).sort(),['controls','firestoreRulesAndIndexes','functionFleet','iamDependencies'].sort(),'Complete before-state readbacks required');for(const [key,p]of Object.entries(preflightPointers)){const r=object(fileBinding(evidence,p));need(r.sourceCommit===measured.source.commit&&time(lastCi)<=time(r.observedAtUtc)&&time(r.observedAtUtc)<=time(r.capturedAtUtc)&&time(r.capturedAtUtc)<=decision&&decision-time(r.observedAtUtc)<=24n*3600n*1000000000n,'Original preflight observation source/time differs: '+key);need(r.measurementPointer&&hex(r.measurementPointer.sha256,64),'Actual preserved child evidence required');fileBinding(evidence,r.measurementPointer);}
 for(const [key,p] of Object.entries(preflightPointers)){const envelope=object(fileBinding(evidence,p));if(key==='controls'){const controls=require('./backendRuntimeControls31.cjs').verifyPreservedControlsBefore31({repoRoot:root,sourceCommit:measured.source.commit,evidenceDirectory:evidence,beforePointer:envelope.measurementPointer,requiredProducerBindings,installedControlRuntime:runtimeProof.installedControlRuntime});need(time(controls.observedAtUtc)===time(envelope.observedAtUtc)&&time(controls.capturedAtUtc)===time(envelope.capturedAtUtc),'Controls raw observation dates differ from envelope');}else{const child=object(fileBinding(evidence,envelope.measurementPointer));const historicalBytes=git(root,['show',aBaselineClosure(measured.source.commit)]);need(hash(historicalBytes)==='3F7065A8540E66B9D879F157861C6DA722A16EFAC21EB9D2FEB9735D71573C45','Historical F closure changed');const backend=object(historicalBytes);require('./backendRuntimeReadbacks31.cjs').verifyMeasuredReadback31({repoRoot:root,candidateSource:measured.source,backendCommit:BASELINE,child,key,earliestUtc:lastCi,latestUtc:approval.decidedAtUtc,expectedRuntimeHash:backend.deployment.sourceRuntimeHash,collectionEnvelope:key==='iamDependencies'?object(fileBinding(evidence,envelope.processPointer)):undefined});}}
 const scheduler=object(fileBinding(evidence,approval.schedulerBaseline));need(scheduler.sourceCommit===measured.source.commit&&time(lastCi)<=time(scheduler.observedAtUtc)&&time(scheduler.observedAtUtc)<=time(scheduler.capturedAtUtc)&&time(scheduler.capturedAtUtc)<=decision,'Original scheduler baseline chronology differs');require('./backendRuntimeControls31.cjs').schedulerControl31(scheduler.response);
 if(requireExecutionHead){need(gtext(root,['branch','--show-current'])==='main'&&gtext(root,['rev-parse','HEAD'])===measured.source.commit&&gtext(root,['rev-parse','refs/remotes/origin/main'])===measured.source.commit,'Execution requires literal main at exact M');need(gtext(root,['status','--porcelain','--untracked-files=normal'])==='','Execution checkout must be clean');}
 return {ok:true,proposalOnly:true,deploymentAuthorized:false,repoRoot:root,authorityRoot:authority,source:measured.source,approvalPointer,decisionAtUtc:approval.decidedAtUtc,executionWindow:approval.executionWindow,projectId:PROJECT,region:REGION,cohorts:measured.cohorts,evidenceDirectory:evidence,runtime,installedControlRuntime:runtimeProof.installedControlRuntime,preflightPointers,schedulerBaseline:approval.schedulerBaseline,requiredProducerBindings,requiredProposalBindings,mainCi:release,securityCi:security};
}
function verifyBackendRuntimeAdmission31(config){return require('./backendRuntimeEvidenceAccess31.cjs').runEvidence31(config,()=>verifyBackendRuntimeAdmission31Inner(config));}
module.exports={verifyBackendRuntimeAdmission31,measureSource31,verifyCi31,verifyGithubObserverRuntime31,verifyRuntimeFiles,verifyProducerBindings,verifyProposalBindings,PROPOSAL_FILES,PATHS,PINS,SCOPE,PROFILE,BASELINE,RELEASE_JOBS,SECURITY_JOBS,helpers:{need,eq,hash,time,git,gtext,local,object,committed,child,fileBinding,source,ancestor,verifyCustodyDelta}};
