'use strict';
const path=require('./backendRuntimeEvidenceAccess31.cjs').path,fs=require('./backendRuntimeEvidenceAccess31.cjs').fs;
const a=require('./backendRuntimeAdmission31.cjs');
const {need,eq,hash,git,fileBinding,object}=a.helpers;
function verifyInstalledGraph31(installed,manifest,lock,expected){
 need(installed.name===manifest.name&&!Object.hasOwn(installed,'problems')&&installed.dependencies&&typeof installed.path==='string','Original installed npm graph required');
 const installedRoot=fs.realpathSync(installed.path),rows=new Map();let edges=0;
 function resolve(from,name,physical=false){let cur=from;while(true){if(path.posix.basename(cur)!=='node_modules'){const key=(cur?cur+'/':'')+'node_modules/'+name;if(physical?fs.existsSync(path.join(installedRoot,key,'package.json')):Object.hasOwn(lock.packages,key))return key;}if(cur==='')return null;const next=path.posix.dirname(cur);cur=next==='.'?'':next;}}
 function visit(row,from,parent,name){
  need(++edges<=20000&&row&&typeof row==='object'&&!Array.isArray(row)&&!row.problems&&!row.invalid&&!row.missing,'Invalid installed runtime graph');
  let rel='',pkg=manifest;
  if(row!==installed){
   need(/^(?:@[a-z0-9._-]+\/)?[a-z0-9._-]+$/i.test(name),'Unsafe installed dependency name');
   const lockedParent=from?lock.packages[from]:manifest,declared={...lockedParent.dependencies,...lockedParent.optionalDependencies,...lockedParent.peerDependencies};need(Object.hasOwn(declared,name),'Installed edge is not declared by immutable parent');
   const target=resolve(from,name),physical=resolve(from,name,true);
   if(Object.keys(row).length===0){const optional=p=>Object.hasOwn(p.optionalDependencies??{},name)||(!Object.hasOwn(p.dependencies??{},name)&&Object.hasOwn(p.peerDependencies??{},name)&&p.peerDependenciesMeta?.[name]?.optional===true);need(optional(lockedParent)&&optional(parent)&&target===null&&physical===null,'Only genuinely absent optional dependency may have an empty npm row');return;}
   need(typeof row.path==='string'&&target!==null&&physical===target,'npm row lacks exact nearest locked and physical dependency');
   const real=fs.realpathSync(row.path);rel=path.relative(installedRoot,real).split(path.sep).join('/');need(rel.startsWith('node_modules/')&&!rel.includes('..')&&fs.realpathSync(path.join(installedRoot,target))===real,'Installed package resolution differs or escapes Functions root');need(expected[rel]?.version===row.version,'Installed version/path differs from immutable lock');pkg=object(fs.readFileSync(path.join(real,'package.json')));need(pkg.version===row.version&&pkg.name===(expected[rel].name??rel.slice(rel.lastIndexOf('node_modules/')+'node_modules/'.length)),'Physical installed package identity differs');for(const key of ['dependencies','optionalDependencies','peerDependencies','peerDependenciesMeta'])eq(pkg[key]??{},expected[rel][key]??{},'Installed dependency declarations differ: '+rel+'/'+key);if(rows.has(rel))eq(rows.get(rel),row.version,'Conflicting duplicate installed package');rows.set(rel,row.version);
  }else{const physical=object(fs.readFileSync(path.join(installedRoot,'package.json')));eq(physical,manifest,'Installed root manifest differs from immutable source');}
  for(const [name,child]of Object.entries(row.dependencies??{}))visit(child,rel,pkg,name);
 }
 visit(installed,'',manifest,'');eq([...rows.keys()].sort(),Object.keys(expected).sort(),'Installed runtime graph population differs');
 // npm legitimately abbreviates deduplicated rows. Reconcile every unique
 // physical package's declared edges independently of those abbreviated rows.
 for(const from of ['',...rows.keys()]){const pkg=from?expected[from]:manifest,all={...pkg.dependencies,...pkg.optionalDependencies,...pkg.peerDependencies};for(const name of Object.keys(all)){const locked=resolve(from,name),physical=resolve(from,name,true),optional=Object.hasOwn(pkg.optionalDependencies??{},name)||(!Object.hasOwn(pkg.dependencies??{},name)&&Object.hasOwn(pkg.peerDependencies??{},name)&&pkg.peerDependenciesMeta?.[name]?.optional===true);need(locked===physical&&(locked!==null||optional),'Installed complete declared edge resolution differs: '+from+' -> '+name);if(physical!==null)need(fs.realpathSync(path.join(installedRoot,physical))===path.join(installedRoot,physical),'Installed complete declared edge follows a symlink');}}
 need(rows.get('node_modules/@grpc/grpc-js')==='1.14.5','Runtime gRPC repair absent');return rows;
}
// Recomputes the installed graph from npm's original --long --all --omit=dev
// output and re-opens its actual package manifests. Summaries alone are rejected.
function verifyRuntimeProofContents31({repoRoot,sourceCommit,evidenceDirectory,proof,runtime}){
 const installed=object(fileBinding(evidenceDirectory,proof.installedDependencies));
 need(installed.name==='crm3-baf-ops-functions'&&!Object.hasOwn(installed,'problems')&&installed.dependencies&&typeof installed.path==='string','Original installed npm graph required');
 const installedRoot=fs.realpathSync(installed.path),manifest=object(git(repoRoot,['show',sourceCommit+':functions/package.json'])),lock=object(git(repoRoot,['show',sourceCommit+':functions/package-lock.json']));
 const graphModule='tools/release/clientBuildToolingCompatibility31.cjs';need(hash(fs.readFileSync(path.join(repoRoot,graphModule)))===hash(git(repoRoot,['show',sourceCommit+':'+graphModule])),'Runtime graph producer differs');const {runtimeReachability}=require(require('./backendRuntimeEvidenceAccess31.cjs').resolveOriginal(path.join(repoRoot,graphModule)));
 const expected=runtimeReachability(manifest,lock),rows=verifyInstalledGraph31(installed,manifest,lock,expected);
 const before=proof.baselineEmittedFiles,after=proof.emittedFiles;need(before&&after&&Object.keys(after).length>0,'Both actual builds need emitted file populations');eq(Object.keys(before).sort(),Object.keys(after).sort(),'Business emitted file population changed');
 const roots={baseline:fs.realpathSync(proof.baselineBuildRoot),candidate:fs.realpathSync(proof.candidateBuildRoot)};
 function emitted(root){const rows={};function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){need(!e.isSymbolicLink(),'Build output symlinks excluded');const file=path.join(dir,e.name);if(e.isDirectory())walk(file);else{need(e.isFile(),'Regular build outputs required');rows[path.relative(path.join(root,'functions'),file).split(path.sep).join('/')]=hash(fs.readFileSync(file));}}}walk(path.join(root,'functions/lib'));return rows;}
 for(const [label,root]of Object.entries(roots)){const expected=label==='baseline'?a.BASELINE:sourceCommit;need(fs.realpathSync(a.helpers.gtext(root,['rev-parse','--show-toplevel']))===root,'Runtime build root must be actual Git top-level');need(a.helpers.gtext(root,['rev-parse','HEAD'])===expected&&a.helpers.gtext(root,['status','--porcelain','--untracked-files=normal'])==='','Runtime build root is not exact clean committed source');const actual=emitted(root),declared=label==='baseline'?before:after;eq(Object.keys(actual).sort(),Object.keys(declared).sort(),'Emitted evidence omits actual build files');for(const p of Object.keys(actual))need(actual[p]===declared[p].sha256,'Actual emitted output differs');}
 for(const name of Object.keys(after)){need(/^lib\/.+\.js(?:\.map)?$/.test(name)&&!name.includes('..'),'Only named compiled Functions files are emitted evidence');const b=fileBinding(evidenceDirectory,before[name]),c=fileBinding(evidenceDirectory,after[name]);need(hash(b)===hash(c),'Business emitted code changed: '+name);}
 const required=['candidate-install','candidate-build','baseline-build','candidate-host-tests','candidate-emulator-tests','dependency-compatibility'];eq(Object.keys(proof.commands??{}).sort(),required.sort(),'Required original runtime command receipts missing');
 const sourceSnapshot=commit=>a.helpers.source(repoRoot,commit);
 for(const name of required){const r=object(fileBinding(evidenceDirectory,proof.commands[name])),baseline=name==='baseline-build',commit=baseline?a.BASELINE:sourceCommit,root=baseline?roots.baseline:roots.candidate;need(r.schemaVersion===1&&r.sourceCommit===commit&&r.exitCode===0,'Original successful source-bound command receipt required');eq(r.sourceBefore,sourceSnapshot(commit),'Command initial source differs');eq(r.sourceAfter,sourceSnapshot(commit),'Command final source differs');need(fs.realpathSync(r.cwd)===root&&r.executable===runtime.nodeExecutable&&r.nodeSha256===runtime.nodeSha256,'Command directory/runtime differs');
  const scripts={'candidate-build':'build','baseline-build':'build','candidate-host-tests':'test','candidate-emulator-tests':'emulator:test:governed','dependency-compatibility':'test:dependency-compat'};const expected=name==='candidate-install'?[runtime.npmCliFile,'ci','--ignore-scripts','--no-audit','--fund=false','--prefix','functions']:[runtime.npmCliFile,'run',scripts[name],...(name==='candidate-build'||baseline||name==='candidate-host-tests'?['--prefix','functions']:[])];eq(r.argv,expected,'Command does not match fixed collection recipe');need(a.helpers.time(proof.startedAtUtc)<=a.helpers.time(r.startedAtUtc)&&a.helpers.time(r.startedAtUtc)<=a.helpers.time(r.completedAtUtc)&&a.helpers.time(r.completedAtUtc)<=a.helpers.time(proof.completedAtUtc),'Command chronology differs');fileBinding(evidenceDirectory,r.stdout);fileBinding(evidenceDirectory,r.stderr);}
 const controlFiles=proof.installedControlRuntime;need(controlFiles&&Object.keys(controlFiles).length>=4,'Installed controls runtime byte bindings required');for(const rel of Object.keys(controlFiles)){need(rel.startsWith('functions/node_modules/')&&!rel.includes('..'),'Unexpected controls runtime path');need(hash(fs.readFileSync(path.join(repoRoot,rel)))===controlFiles[rel],'Installed controls runtime byte binding differs');}for(const p of ['functions/node_modules/typescript/package.json','functions/node_modules/firebase-functions/package.json','functions/node_modules/typescript/lib/typescript.js','functions/node_modules/firebase-functions/lib/runtime/manifest.js'])need(Object.hasOwn(controlFiles,p),'Mandatory controls runtime producer absent');
 const prepared=object(fileBinding(evidenceDirectory,proof.intendedHashInputs));need(prepared.documentType==='firebase-cli-approved-intended-hash-inputs'&&prepared.actualCliPreparationCaptured===false,'Pre-decision intent must not claim actual CLI preparation');need(a.helpers.time(proof.startedAtUtc)<=a.helpers.time(prepared.startedAtUtc)&&a.helpers.time(prepared.startedAtUtc)<=a.helpers.time(prepared.completedAtUtc)&&a.helpers.time(prepared.completedAtUtc)<=a.helpers.time(proof.completedAtUtc),'Prepared hash input chronology differs');const names=Object.keys(object(git(repoRoot,['show',sourceCommit+':release/function-fleet-runtime-identity-policy.json'])).functionBindings).sort();require('./backendRuntimeClosure31.cjs').endpointRuntimeHashes31({sourceArchiveHash:prepared.sourceArchiveHash,inputs:prepared,runtime,names,source:a.helpers.source(repoRoot,sourceCommit)});
 return {ok:true,installedRuntimePathCount:rows.size,emittedFileCount:Object.keys(after).length,installedControlRuntime:controlFiles};
}
module.exports={verifyRuntimeProofContents31,verifyInstalledGraph31};
