'use strict';
// Re-adjudicates preserved raw collector outputs. No remote requests.
const path=require('./backendRuntimeEvidenceAccess31.cjs').path;
const a=require('./backendRuntimeAdmission31.cjs');
const {need,eq,hash,time,git,object}=a.helpers;
function load(repoRoot,commit,file){const raw=git(repoRoot,['show',commit+':'+file]);const fs=require('./backendRuntimeEvidenceAccess31.cjs').fs,actual=fs.realpathSync(path.join(repoRoot,file));need(hash(fs.readFileSync(actual))===hash(raw),'Loaded producer differs from source: '+file);return require(actual);}
function verifyMeasuredReadback31({repoRoot,candidateSource,backendCommit,child,key,earliestUtc,latestUtc,expectedRuntimeHash,collectionEnvelope}){
 const seals=load(repoRoot,candidateSource.commit,'tools/release/collectProductionGlobalPullBackend.js');seals.verifyReceiptSeal(child,'Build31 '+key);
 for(const p of [child.source?.before,child.source?.after])need(p?.commit===candidateSource.commit&&p.tree===candidateSource.tree&&p.originMain===candidateSource.commit&&p.branch==='main'&&p.governedWorktreeClean===true&&p.materialChangeCount===0&&Array.isArray(p.materialPathSha256)&&p.materialPathSha256.length===0,'Readback exact clean source differs');
 // The existing IAM collector has no start field. Its untouched sealed bytes
 // stay intact; an independently hash-bound process envelope carries that time.
 let observed=key==='functionFleet'?child.outputs?.schedulerBacklog?.observedAtUtc:child.collectionStartedAtUtc;
 if(key==='iamDependencies'){need(collectionEnvelope?.sourceCommit===candidateSource.commit&&collectionEnvelope.collector==='tools/release/collectFunctionsIamDependenciesReadback.js'&&collectionEnvelope.exitCode===0&&collectionEnvelope.mode===(backendCommit===candidateSource.commit?'strict':'observe'),'Original IAM process envelope required');eq(collectionEnvelope.sourceBefore,child.source.before,'IAM process initial source differs');eq(collectionEnvelope.sourceAfter,child.source.after,'IAM process final source differs');need(collectionEnvelope.measurementSha256===hash(Buffer.from(JSON.stringify(child)))||collectionEnvelope.canonicalReceiptSha256===child.receiptSha256,'IAM process does not bind the original sealed receipt');observed=collectionEnvelope.startedAtUtc;need(time(child.capturedAtUtc)<=time(collectionEnvelope.completedAtUtc)&&time(collectionEnvelope.completedAtUtc)<=time(latestUtc),'IAM process completion chronology differs');}
 need(time(earliestUtc)<=time(observed)&&time(observed)<=time(child.capturedAtUtc)&&time(child.capturedAtUtc)<=time(latestUtc),'Original readback observation chronology differs');
 const files={functionFleet:'tools/release/collectFunctionFleetRuntimeIdentityReadback.js',iamDependencies:'tools/release/collectFunctionsIamDependenciesReadback.js',firestoreRulesAndIndexes:'tools/release/collectFirestoreRulesIndexesReadback.js'};need(files[key],'Unknown readback kind');const collector=load(repoRoot,candidateSource.commit,files[key]);
 let result;
 if(key==='firestoreRulesAndIndexes'){
  const rulesRaw=git(repoRoot,['show',backendCommit+':firestore.rules']).toString('utf8'),indexRaw=git(repoRoot,['show',backendCommit+':firestore.indexes.json']).toString('utf8');const b=collector.sourceIndexSetBinding(JSON.parse(indexRaw),indexRaw),{rules,indexes}=child.outputs;
  need(rules.sourceSha256.toUpperCase()===hash(Buffer.from(rulesRaw))&&rules.sourceByteCount===Buffer.byteLength(rulesRaw),'Rules do not match immutable source');need(indexes.sourceCount===b.count&&indexes.sourceSetSha256.toUpperCase()===b.indexSetSha256.toUpperCase()&&indexes.sourceFieldOverrideCount===b.fieldOverrideCount&&indexes.sourceFieldOverrideSha256.toUpperCase()===b.fieldOverrideSetSha256.toUpperCase(),'Indexes do not match immutable source');
  result=collector.adjudicateReadback({projectId:'crm3-baf-ops-b8638',sourceBefore:child.source.before,sourceAfter:child.source.after,rules,indexes,observe:false});
 }else{
  const policy=object(git(repoRoot,['show',backendCommit+':'+collector.POLICY_PATH])),outputs=child.outputs,names=key==='functionFleet'?Object.keys(policy.functionBindings).sort():[...policy.sourceFunctionExports].sort();
  eq(outputs.functions.map(r=>r.name).sort(),names,'Measured Function population differs');const labels=typeof expectedRuntimeHash==='string'?Object.fromEntries(names.map(n=>[n,expectedRuntimeHash])):expectedRuntimeHash;eq(Object.keys(labels??{}).sort(),names,'Expected endpoint label population differs');need(Object.values(labels).every(x=>typeof x==='string'&&/^[0-9a-f]{40}$/.test(x))&&outputs.functions.every(r=>r.firebaseFunctionsHash===labels[r.name]),'Function runtime labels differ');
  const common={projectId:'crm3-baf-ops-b8638',region:'asia-south1',policy,sourceBefore:child.source.before,sourceAfter:child.source.after};
  if(key==='functionFleet')result=collector.adjudicateReadback({...common,phase:'final',probeCallables:true,discoveredSourceExports:names,live:{...outputs,backlog:outputs.schedulerBacklog,emailMap:collector.accountEmailMap(policy,'crm3-baf-ops-b8638'),expectedRoles:collector.expectedProjectRoles(policy,'crm3-baf-ops-b8638')}});
  else{const summary=commit=>collector.summarizePackageState({packageJsonRaw:git(repoRoot,['show',commit+':functions/package.json']).toString('utf8'),packageLockRaw:git(repoRoot,['show',commit+':functions/package-lock.json']).toString('utf8'),trackedPackages:policy.trackedRuntimePackages}),deps=summary(backendCommit);eq(outputs.discoveredSourceFunctionExports,names,'Discovered Function exports differ');const inputs={...common,project:outputs.project,iam:outputs.iam,functions:outputs.functions,discoveredSourceExports:names};
   if(backendCommit!==candidateSource.commit){const candidateDeps=summary(candidateSource.commit);eq(outputs.currentSourceDependencies,candidateDeps,'Preserved raw candidate-M dependency observation differs');need(child.mode==='OBSERVE','Predeployment candidate mismatch must remain an original OBSERVE capture');const rawReplay=collector.adjudicateReadback({...inputs,observe:true,currentDependencies:candidateDeps});for(const field of ['decision','failedChecks','checks','posture','mode'])eq(child[field],rawReplay.evidence[field],'Original candidate-M hold was altered');result=collector.adjudicateReadback({...inputs,observe:false,currentDependencies:deps});}
   else{eq(outputs.currentSourceDependencies,deps,'Observed dependency inventory differs from actual backend source');result=collector.adjudicateReadback({...inputs,observe:false,currentDependencies:deps});}
  }
 }
 need(result.failedChecks.length===0&&Object.values(result.evidence.checks).every(v=>v===true),'Strict measured readback did not pass');
 const fields=key==='firestoreRulesAndIndexes'?['schemaVersion','evidenceType','mode','projectId','decision','failedChecks','checks','mutationBoundary','privacyBoundary']:['schemaVersion','evidenceType','projectId','region','decision','failedChecks','checks','posture','mutationBoundary','privacyBoundary',...(key==='functionFleet'?['phase']:['mode','gateIds','closureScope'])];if(!(key==='iamDependencies'&&backendCommit!==candidateSource.commit))for(const field of fields)eq(child[field],result.evidence[field],'Readback decision disagrees with raw replay: '+field);
 if(key==='iamDependencies')need(result.evidence.posture.holds.length===0&&result.evidence.posture.decision==='PASS_RUNTIME_IDENTITY_DEPENDENCY_POSTURE','IAM/dependency hold remains');
 return {ok:true,observedAtUtc:observed,capturedAtUtc:child.capturedAtUtc};
}
module.exports={verifyMeasuredReadback31,load};
