'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process');
const {git}=require('./backendRuntimeAdmission31.cjs').helpers;
const {verifyMetadataOnlySuccessor31}=require('./backendRuntimeClosedReplay31.cjs');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'crm31-safe-git-'));
function g(...args){return cp.execFileSync('git',['-c','user.name=Local fixture','-c','user.email=fixture@invalid.example','-c','core.autocrlf=false','-C',root,...args],{encoding:'utf8',windowsHide:true}).trim();}
g('init');fs.writeFileSync(path.join(root,'pubspec.yaml'),'name: fixture\nversion: 1.0.0+30\n');fs.writeFileSync(path.join(root,'pubspec.lock'),'packages: {}\n');g('add','.');g('commit','-m','Synthetic M');const M=g('rev-parse','HEAD');
test('actual guarded Git status never executes raw fsmonitor command',()=>{
  const marker=path.join(root,'marker'),script=path.join(root,'monitor.sh');fs.writeFileSync(script,'#!/bin/sh\nprintf unsafe > "'+marker.replaceAll('\\','/')+'"\n');g('config','core.fsmonitor',script.replaceAll('\\','/'));
  git(root,['status','--porcelain']);assert.equal(fs.existsSync(marker),false);g('config','--unset','core.fsmonitor');fs.unlinkSync(script);
});
for(const [section,value]of [['filter.bad.clean','sh -c touch marker'],['include.path','external.conf'],['diff.bad.textconv','sh -c touch marker']])test('raw executable/config include refusal: '+section,()=>{g('config',section,value);assert.throws(()=>git(root,['status','--porcelain']),/configuration/);g('config','--remove-section',section.split('.').slice(0,-1).join('.'));});
test('process GIT_CONFIG injected fsmonitor is not inherited',()=>{process.env.GIT_CONFIG_COUNT='1';process.env.GIT_CONFIG_KEY_0='core.fsmonitor';process.env.GIT_CONFIG_VALUE_0='invalid-executable';try{assert.doesNotThrow(()=>git(root,['status','--porcelain']));}finally{delete process.env.GIT_CONFIG_COUNT;delete process.env.GIT_CONFIG_KEY_0;delete process.env.GIT_CONFIG_VALUE_0;}});
test('governed version-only source successor passes while dependency lock mutation fails',()=>{fs.writeFileSync(path.join(root,'pubspec.yaml'),'name: fixture\nversion: 1.0.0+31\n');g('add','.');g('commit','-m','Synthetic metadata');const S=g('rev-parse','HEAD');assert.equal(verifyMetadataOnlySuccessor31(root,M,S),true);fs.appendFileSync(path.join(root,'pubspec.lock'),'changed: true\n');g('add','.');g('commit','-m','Synthetic unsafe dependency successor');assert.throws(()=>verifyMetadataOnlySuccessor31(root,M,g('rev-parse','HEAD')),/pubspec.lock/);});

test('a Git-file redirect is rejected before native Git executes',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'crm31-gitfile-'));fs.writeFileSync(path.join(dir,'.git'),'gitdir: '+path.join(root,'.git')+'\n');assert.throws(()=>git(dir,['status','--porcelain']),/real self-contained/);});
test('core.worktree redirection is rejected',()=>{g('config','core.worktree',os.tmpdir());try{assert.throws(()=>git(root,['status','--porcelain']),/configuration/);}finally{g('config','--unset','core.worktree');}});
test('a version-only pubspec cannot become executable metadata',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'crm31-mode-'));const cmd=(...args)=>cp.execFileSync('git',['-c','user.name=Local fixture','-c','user.email=fixture@invalid.example','-C',dir,...args],{encoding:'utf8',windowsHide:true}).trim();cmd('init');fs.writeFileSync(path.join(dir,'pubspec.yaml'),'name: fixture\nversion: 1.0.0+30\n');cmd('add','.');cmd('commit','-m','Synthetic M');const m=cmd('rev-parse','HEAD');fs.writeFileSync(path.join(dir,'pubspec.yaml'),'name: fixture\nversion: 1.0.0+31\n');cmd('add','.');cmd('update-index','--chmod=+x','pubspec.yaml');cmd('commit','-m','Synthetic mode substitution');assert.throws(()=>verifyMetadataOnlySuccessor31(dir,m,cmd('rev-parse','HEAD')),/nonexecutable/);});
