'use strict';
// Synthetic/local tests only. No actual preparation, HTTP call or deployment.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const a=require('./backendRuntimeAdmission31.cjs'),gate=require('./backendRuntimeExecutionAdmission31.cjs'),t=require('./runtimeDeploymentTransportGuard31.cjs');
const h=a.helpers.hash,source={commit:'1'.repeat(40),tree:'2'.repeat(40),functionsTree:'3'.repeat(40)};
function consent(){const approval={source,decidedAtUtc:'2026-10-01T20:00:00Z'},originalMessage={evidenceType:gate.TRUSTED_MESSAGE_TYPE,actorKind:'human-owner',conversationId:'synthetic-conversation',messageId:'synthetic-message',source,exactQuestion:gate.ownerInstruction(source),exactText:'Yes—deploy this exact reviewed source',actualProductionDeploymentAuthorized:true,codePreparationOnly:false,receiptTimeBasis:'first-receipt-observation',receivedAtUtc:'2026-10-01T19:59:00Z',provenanceBasis:'operator-retained-direct-human-message',machineAuthenticatedHuman:false,recordedBy:'synthetic-test-operator'},owner={schemaVersion:2,authorizationType:'direct-human-production-deployment',deploymentAction:gate.OWNER_ACTION,source,scope:a.SCOPE,actualProductionDeploymentAuthorized:true,codePreparationOnly:false,ownerInstruction:originalMessage.exactText,authorizedAtUtc:originalMessage.receivedAtUtc,recordedAtUtc:'2026-10-01T19:59:30Z'};return {approval,owner,originalMessage,source};}
test('explicit source/action contract accepts a structurally complete local fixture without claiming human authentication',()=>assert.equal(gate.verifyExplicitDeploymentOwner31(consent()),true));
for(const [name,mutate]of [
 ['today preparation reply',x=>{x.originalMessage.exactText='Approve publication of 128aec81 and backend release-code preparation.';x.owner.ownerInstruction=x.originalMessage.exactText;}],
 ['preparation-only flag',x=>x.originalMessage.codePreparationOnly=true],
 ['no deployment approval',x=>x.owner.actualProductionDeploymentAuthorized=false],
 ['wrong source',x=>x.owner.source={...source,commit:'4'.repeat(40)}],
 ['wrong action',x=>x.owner.deploymentAction='prepare-code'],
 ['claimed machine human authentication',x=>x.originalMessage.machineAuthenticatedHuman=true],
 ['synthetic authority marker',x=>x.approval.testFixtureOnly=true],
 ['Rules scope widening',x=>x.owner.scope={...a.SCOPE,firestoreRulesDeployment:true}],
 ['earlier original receipt relabelled as later consent',x=>x.owner.authorizedAtUtc='2026-10-01T19:59:20Z'],
 ['missing receipt time basis',x=>delete x.originalMessage.receiptTimeBasis],
 ['later owner receipt',x=>x.originalMessage.receivedAtUtc='2026-10-01T20:01:00Z'],
 ['generic yes without bound question',x=>x.originalMessage.exactQuestion='Can I prepare release code?'],
])test('execution consent rejects '+name,()=>{const x=consent();mutate(x);assert.throws(()=>gate.verifyExplicitDeploymentOwner31(x));});
for(const key of ['NODE_OPTIONS','NODE_PATH','NODE_EXTRA_CA_CERTS','NODE_TLS_REJECT_UNAUTHORIZED','SSL_CERT_FILE','SSL_CERT_DIR','FIREBASE_CONFIG','FIREBASE_TOKEN','FIREBASE_AUTH_EMULATOR_HOST','GOOGLE_APPLICATION_CREDENTIALS','npm_config_script_shell','HTTPS_PROXY'])test('process environment refuses '+key,()=>assert.throws(()=>gate.cleanEnvironment31({[key]:'unreviewed'})));
test('process environment preserves account-storage location without arbitrary environment',()=>{const result=gate.cleanEnvironment31({USERPROFILE:'C:/synthetic',APPDATA:'C:/synthetic/app',ARBITRARY:'x'});assert.equal(result.USERPROFILE,'C:/synthetic');assert.equal(result.ARBITRARY,undefined);});
test('deep synthetic contamination is rejected',()=>assert.throws(()=>gate.rejectSynthetic({commands:{one:{notActualExecution:true}}})));

function live(){const head='4'.repeat(40),issue_url='https://api.github.com/repos/abhishekvatsa/crm3_baf_ops/issues/391',request={id:1001,issue_url,body:'Review exact head '+head,created_at:'2026-10-01T19:16:00Z'},review={id:1002,issue_url,body:'No major issues. **Reviewed commit:** `'+head.slice(0,10)+'`',created_at:'2026-10-01T19:21:00Z',user:{login:'chatgpt-codex-connector[bot]'},performed_via_github_app:{slug:'chatgpt-codex-connector'}},pr={number:391,merged:true,merge_commit_sha:source.commit,head:{sha:head},base:{sha:source.commit,ref:'main',repo:{full_name:'abhishekvatsa/crm3_baf_ops'}},merged_at:'2026-10-01T19:22:00Z'};
 const ci=(kind,id)=>({schemaVersion:1,evidenceType:kind==='release'?'github-exact-main-release-gate':'github-exact-main-codeql',repository:'abhishekvatsa/crm3_baf_ops',sourceCommit:source.commit,sourceTree:source.tree,capturedAtUtc:'2026-10-01T19:55:00Z',pullRequest:pr,run:{id,run_attempt:1,repository:{full_name:'abhishekvatsa/crm3_baf_ops'},head_sha:source.commit,head_branch:'main',event:'push',path:kind==='release'?'.github/workflows/release-gate.yml':'.github/workflows/codeql.yml',status:'completed',conclusion:'success',created_at:'2026-10-01T19:23:00Z',updated_at:'2026-10-01T19:50:00Z'},jobs:{total_count:(kind==='release'?a.RELEASE_JOBS:a.SECURITY_JOBS).length,jobs:(kind==='release'?a.RELEASE_JOBS:a.SECURITY_JOBS).map((name,i)=>({id:id*10+i,run_id:id,run_attempt:1,head_sha:source.commit,name,status:'completed',conclusion:'success',completed_at:'2026-10-01T19:49:00Z'}))}});
 return {source,approval:{decidedAtUtc:'2026-10-01T20:00:00Z',normalMergeParents:['0'.repeat(40),head],mainCiRun:{id:1,runAttempt:1},securityCiRun:{id:2,runAttempt:1},settledSourceReview:{kind:'bot-issue-comment-no-findings',reviewer:'chatgpt-codex-connector[bot]',headCommit:head,response:{id:review.id,bodySha256:h(Buffer.from(review.body))},request:{id:request.id,bodySha256:h(Buffer.from(request.body))}}},release:ci('release',1),security:ci('security',2),mainRef:{ref:'refs/heads/main',object:{sha:source.commit}},pr,review,reviewRequest:request,reviewedHeadCommit:head,reviews:{nodes:[],pageInfo:{hasNextPage:false}},threads:{nodes:[],pageInfo:{hasNextPage:false}},nowUtc:'2026-10-01T20:01:00Z'};
}
test('synthetic full request/abbreviated positive bot response validates with exact resolved commit and postmerge base SHA',()=>assert.equal(gate.verifyLiveGitHubRecords31(live()),true));
for(const [name,mutate]of [['changed live main',x=>x.mainRef.object.sha='0'.repeat(40)],['wrong resolved prefix',x=>x.reviewedHeadCommit='0'.repeat(40)],['old run attempt',x=>x.release.jobs.jobs[0].run_attempt=2],['outstanding changes requested',x=>x.reviews.nodes.push({author:{login:'reviewer'},submittedAt:'2026-10-01T19:30:00Z',state:'CHANGES_REQUESTED'})],['unresolved thread',x=>x.threads.nodes.push({isResolved:false})],['truncated review population',x=>x.reviews.pageInfo.hasNextPage=true],['quota instead of review',x=>{x.review.body='Review usage allowance exhausted';x.approval.settledSourceReview.response.bodySha256=h(Buffer.from(x.review.body));}],['arbitrary comment',x=>{x.review.body='COMMENTED on the PR';x.approval.settledSourceReview.response.bodySha256=h(Buffer.from(x.review.body));}]])test('live gate rejects '+name,()=>{const x=live();mutate(x);assert.throws(()=>gate.verifyLiveGitHubRecords31(x));});

const names=Array.from({length:19},(_,i)=>'fn'+i),project='projects/crm3-baf-ops-b8638/locations/asia-south1/functions/',zip=Buffer.from('local synthetic archive');
function transport(){const baseline={name:project+'fn0',buildConfig:{runtime:'nodejs22',entryPoint:'fn0',source:{storageSource:{bucket:'old',object:'old',generation:'1'}}},labels:{'firebase-functions-hash':'a'.repeat(40),preserved:'yes'},serviceConfig:{environmentVariables:{CRM3_MUTATING_CALLABLE_ENFORCE_APP_CHECK:'false'},maxInstanceCount:20}},guard=new t.RuntimeDeploymentTransportGuard31({names:['fn0'],allNames:names,baselineFunctions:{fn0:baseline},sourceArchiveHash:'b'.repeat(40),endpointRuntimeHashes:Object.fromEntries(names.map(n=>[n,'c'.repeat(40)])),phase:'callables'});return {guard,baseline};}
const cf={opts:{urlPrefix:'https://cloudfunctions.googleapis.com',apiVersion:'v2'}};
function prepared(guard){guard.preparedMatches({sourceArchiveHash:'b'.repeat(40),endpointRuntimeHashes:Object.fromEntries(names.map(n=>[n,'c'.repeat(40)])),archiveSha256:h(zip),archiveBytes:zip.length});}
test('no cloud write before actual prepared-input comparison',()=>assert.throws(()=>transport().guard.before(cf,{method:'POST',path:project.slice(0,-1)+':generateUploadUrl'})));
test('actual verified ZIP binding is adopted only with actual capture',()=>{const{guard}=transport();prepared(guard);assert.equal(guard.archiveSha256,h(zip));assert.equal(guard.archiveBytes,zip.length);});
function patchCase(){const{guard,baseline}=transport();prepared(guard);const location={bucket:'verified',object:'new',generation:'2'};guard.after({kind:'generate-upload'},{body:{uploadUrl:'https://storage.googleapis.com/synthetic?GoogleAccessId=x',storageSource:location}});const proposed=structuredClone(baseline);proposed.buildConfig.source.storageSource=location;proposed.labels['firebase-functions-hash']='c'.repeat(40);return {guard,request:{method:'PATCH',path:project+'fn0',body:proposed,queryParams:{updateMask:'name,buildConfig.source,buildConfig.runtime,buildConfig.entryPoint,labels,serviceConfig.environmentVariables,serviceConfig.maxInstanceCount'}}};}
test('exact source/label update preserving all other controls is admitted structurally',()=>{const x=patchCase();assert.equal(x.guard.before(cf,x.request).kind,'function-update');});
for(const[name,mutate]of [['removed preserved label',x=>delete x.request.body.labels.preserved],['changed enforcement',x=>x.request.body.serviceConfig.environmentVariables.CRM3_MUTATING_CALLABLE_ENFORCE_APP_CHECK='true'],['changed capacity',x=>x.request.body.serviceConfig.maxInstanceCount=21],['unknown source',x=>x.request.body.buildConfig.source.storageSource.object='other'],['wrong endpoint label',x=>x.request.body.labels['firebase-functions-hash']='d'.repeat(40)],['wildcard mask',x=>x.request.queryParams.updateMask='*'],['wrong cohort',x=>x.request.path=project+'fn1']])test('transport refuses '+name,()=>{const x=patchCase();mutate(x);assert.throws(()=>x.guard.before(cf,x.request));});
test('a second Function update cannot silently retry',()=>{const x=patchCase();x.guard.before(cf,x.request);assert.throws(()=>x.guard.before(cf,x.request),/retry/);});
for(const [host,method,url]of [['serviceusage.googleapis.com','POST','/v1/projects/crm3-baf-ops-b8638/services/x:enable'],['cloudresourcemanager.googleapis.com','POST','/v1/projects/crm3-baf-ops-b8638:setIamPolicy'],['cloudscheduler.googleapis.com','POST','/v1/projects/crm3-baf-ops-b8638/locations/asia-south1/jobs/x:run'],['secretmanager.googleapis.com','GET','/v1/projects/crm3-baf-ops-b8638/secrets/x/versions/1:access'],['cloudfunctions.googleapis.com','DELETE','/v2/'+project+'fn0']])test('forbidden operation '+host+url,()=>{const{guard}=transport();prepared(guard);assert.throws(()=>guard.before({opts:{urlPrefix:'https://'+host}},{method,path:url}));});
test('URL effective hostname/path/method overrides are inspected',()=>{const r=t.effectiveRequest31(new URL('https://cloudfunctions.googleapis.com/safe'),{hostname:'evil.invalid',path:'/changed?q=1',method:'DELETE'},'https:');assert.equal(r.url.href,'https://evil.invalid/changed?q=1');assert.equal(r.method,'DELETE');});
test('signed upload query is retained exactly in effective URI',()=>{const u=t.urlOf({opts:{urlPrefix:'https://storage.googleapis.com'}},{path:'/bucket/object',queryParams:new URLSearchParams('GoogleAccessId=x&Signature=y')});assert.equal(u.search,'?GoogleAccessId=x&Signature=y');});
test('wire JSON body binding changes with controls',()=>assert.notEqual(t.bodyBinding31({body:{max:20}}),t.bodyBinding31({body:{max:21}})));

test('observer binary binding is checked without executing the measured file',()=>{const file=process.execPath,digest=h(fs.readFileSync(file)),runtime={githubExecutable:file,githubExecutableSha256:digest};assert.deepEqual(a.verifyGithubObserverRuntime31(runtime),{executable:file,sha256:digest});assert.throws(()=>a.verifyGithubObserverRuntime31({}),/GitHub observer/);assert.throws(()=>a.verifyGithubObserverRuntime31({...runtime,githubExecutableSha256:'0'.repeat(64)}),/GitHub observer/);});
test('historical observation cannot omit or substitute the declared observer identity',()=>{const runtime={githubExecutable:process.execPath,githubExecutableSha256:h(fs.readFileSync(process.execPath))};for(const observer of [undefined,{executable:'unreviewed',sha256:runtime.githubExecutableSha256},{executable:runtime.githubExecutable,sha256:'0'.repeat(64)}])assert.throws(()=>gate.verifyPreservedLiveGitHub31({observer},{runtime},{}),/observer/);});
