"use strict";
// Core portable clean-install regression. Local execution needs the explicit
// approval recorded for this new fixture; no existing dependency tree is used.
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),os=require("node:os"),cp=require("node:child_process"),zlib=require("node:zlib");
const api=require("./business31NpmBinMaterialization.cjs"),transport=require("./privateEvidenceBundle31.cjs");
function put(root,name,raw,mode){const file=path.join(root,...name.split("/"));fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,raw,mode?{mode}:undefined);return file;}
function npmCli(){const candidates=[process.env.npm_execpath,path.join(path.dirname(process.execPath),"node_modules/npm/bin/npm-cli.js"),path.resolve(path.dirname(process.execPath),"../lib/node_modules/npm/bin/npm-cli.js")].filter(Boolean);const file=candidates.find(p=>fs.existsSync(p));assert.ok(file,"This selected clean-install test requires the governed Node runtime's npm; no skipped substitute");return fs.realpathSync(file);}
const maps=root=>Object.fromEntries(Object.entries(api.ROOTS).map(([k,d])=>[k,api.scan31(path.join(root,d)).files]));
test("genuine offline npm clean installation preserves three-root launcher behavior and byte-only replay",{timeout:120000},t=>{
  const supplied=process.env.BUSINESS31_OFFLINE_FIXTURE_ROOT;let root;
  if(supplied){assert.equal(path.isAbsolute(supplied),true);assert.equal(path.dirname(path.resolve(supplied)),fs.realpathSync(path.dirname(supplied)));assert.equal(fs.existsSync(supplied),false,"Fixture root must be fresh and exclusively owned");fs.mkdirSync(supplied);root=fs.realpathSync(supplied);}else root=fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()),"business31-offline-npm-"));
  put(root,"OWNERSHIP.json",JSON.stringify({fixtureOnly:true,platform:process.platform,root}));t.diagnostic("Retained isolated fixture: "+root);
  const packageRoot=path.join(root,"package"),build=path.join(root,"build"),cache=path.join(root,"cache"),tarballs=path.join(root,"tarballs");for(const dir of [packageRoot,build,tarballs])fs.mkdirSync(dir);
  put(packageRoot,"package.json",JSON.stringify({name:"build31-bin-probe",version:"1.0.0",bin:{"build31-bin-probe":"bin/probe.js"}}));put(packageRoot,"bin/probe.js","#!/usr/bin/env node\nconsole.log(JSON.stringify({args:process.argv.slice(2),file:__filename}));\n",0o755);
  const user=put(root,"npm-user-config",""),global=put(root,"npm-global-config",""),npm=npmCli(),env={...process.env};for(const key of Object.keys(env))if(/^npm_config_/i.test(key)||/^NODE_OPTIONS$/i.test(key)||/^NODE_PATH$/i.test(key))delete env[key];
  Object.assign(env,{npm_config_cache:cache,npm_config_userconfig:user,npm_config_globalconfig:global,npm_config_offline:"true",npm_config_audit:"false",npm_config_fund:"false",npm_config_update_notifier:"false"});
  let number=0;const run=(cwd,args)=>{const prefix=String(++number).padStart(2,"0"),startedAtUtc=new Date().toISOString(),result=cp.spawnSync(process.execPath,[npm,...args],{cwd,env,encoding:"utf8",windowsHide:true,timeout:90000,maxBuffer:4*1024*1024});put(root,"commands/"+prefix+"-stdout.txt",result.stdout??"");put(root,"commands/"+prefix+"-stderr.txt",result.stderr??"");put(root,"commands/"+prefix+"-record.json",JSON.stringify({cwd,argv:[npm,...args],startedAtUtc,completedAtUtc:new Date().toISOString(),exitCode:result.status,signal:result.signal,error:result.error?String(result.error):null}));assert.equal(result.error,undefined);assert.equal(result.status,0,result.stderr);return result.stdout;};
  const packed=JSON.parse(run(packageRoot,["pack","--offline","--json","--ignore-scripts","--pack-destination",tarballs])),tar=path.join(tarballs,packed[0].filename);
  for(const [kind,directory] of Object.entries(api.ROOTS)){
    const app=path.dirname(path.join(build,directory));fs.mkdirSync(app,{recursive:true});put(app,"package.json",JSON.stringify({name:"build31-"+kind,version:"1.0.0",private:true,scripts:{build:'build31-bin-probe "with spaces"',test:'build31-bin-probe "test arg"'},dependencies:{"build31-bin-probe":"file:"+tar.replace(/\\/g,"/")}}));
    run(app,["install","--offline","--package-lock-only","--ignore-scripts","--no-audit","--fund=false"]);run(app,["ci","--offline","--ignore-scripts","--no-audit","--fund=false"]);
    assert.equal(fs.lstatSync(path.join(build,directory,".bin/build31-bin-probe")).isSymbolicLink(),process.platform!=="win32","Actual npm executable shape must match this platform");
  }
  const receipt=api.materializeNpmBins31({buildRoot:build});put(root,"materialization.json",JSON.stringify(receipt));
  const verify=target=>api.verifyNpmBinMaterialization31({receipt,buildRoot:target,nodeExecutable:{path:fs.realpathSync(process.execPath),sha256:api.sha(fs.readFileSync(process.execPath))},producerSha256:api.sha(fs.readFileSync(require.resolve("./business31NpmBinMaterialization.cjs"))),fileMaps:maps(target)});
  assert.equal(verify(build).recordedMaterializationVerified,true);
  for(const [kind,directory]of Object.entries(api.ROOTS)){for(const command of ["build","test"]){const value=JSON.parse(run(path.dirname(path.join(build,directory)),["run",command,"--silent"]).trim());assert.deepEqual(value.args,[command==="build"?"with spaces":"test arg"]);assert.ok(value.file.replace(/\\/g,"/").endsWith("/node_modules/build31-bin-probe/bin/probe.js"));}assert.equal(receipt.roots[kind].aliases.length,process.platform==="win32"?0:1);}
  const originals=[];for(const directory of Object.values(api.ROOTS))for(const name of Object.keys(api.scan31(path.join(build,directory)).files))originals.push({path:directory+"/"+name,raw:fs.readFileSync(path.join(build,directory,name))});
  const members=originals.map(({path,raw})=>{const compressed=zlib.gzipSync(raw);return {path,bytes:raw.length,sha256:api.sha(raw),encoding:"gzip",compressedBytes:compressed.length,compressedSha256:api.sha(compressed),base64:compressed.toString("base64")};}),inventory=Object.fromEntries(members.map(m=>[m.path,{bytes:m.bytes,sha256:m.sha256}])),source={commit:"1".repeat(40),tree:"2".repeat(40),functionsTree:"3".repeat(40)},relocation={};
  const bundle=Buffer.from(JSON.stringify({schemaVersion:2,documentType:"build31-private-business-evidence-bundle",encoding:transport.BUNDLE_ENCODING,source,members,relocation})),descriptor={bundleEncoding:transport.BUNDLE_ENCODING,expandedBytes:members.reduce((n,m)=>n+m.bytes,0),source,membersSha256:api.sha(api.canonical(inventory)),relocationSha256:api.sha(api.canonical(relocation)),custody:{provider:"gcs",bucket:transport.BUCKET,objectName:"release-custody/build-31/business-backend/"+source.commit+"/fixture/private-replay-bundle.json",generation:"1",bytes:bundle.length,sha256:api.sha(bundle)}};
  const extracted=transport.extractVerifiedBundle31(bundle,descriptor,path.join(root,"extracted"),"business");assert.equal(verify(extracted.root).recordedMaterializationVerified,true);
  for(const {path:name}of originals){const file=path.join(extracted.root,name);assert.equal(fs.lstatSync(file).isSymbolicLink(),false);if(process.platform!=="win32")assert.equal(fs.statSync(file).mode&0o777,0o600);}
  const target=originals.find(row=>row.path.endsWith("/bin/probe.js"));fs.appendFileSync(path.join(extracted.root,target.path),"// tampered fixture byte\n");assert.throws(()=>verify(extracted.root),/population|declaration\/target/);
  put(root,"RESULT.json",JSON.stringify({passed:true,platform:process.platform,realOfflineCleanInstall:true,posixAliases:process.platform!=="win32",credentialOrDeploymentAuthority:false}));
});
