"use strict";
const bootstrapEntry31 = require("./business31CaptureBootstrap.cjs");
if (!bootstrapEntry31.isComponentChild31("prepared-hook")) {
  bootstrapEntry31.runComponentSuiteTest31("prepared-hook");
} else {
"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto"),cp=require("node:child_process");
const root=path.resolve(__dirname,"../..");
const out=fs.mkdtempSync(path.join(fs.realpathSync(require("node:os").tmpdir()),"business31-prepared-hook-"));
// This Node test worker owns the isolated profile; no user profile is changed.
const environmentKeys=new Set(["PATH","SYSTEMROOT","WINDIR","COMSPEC","PATHEXT","NODE_TEST_CONTEXT"]);
for(const key of Object.keys(process.env))if(!environmentKeys.has(key.toUpperCase()))delete process.env[key];
for(const key of ["HOME","USERPROFILE","APPDATA","LOCALAPPDATA","XDG_CONFIG_HOME","TEMP","TMP"]){
 const directory=path.join(out,key);fs.mkdirSync(directory);process.env[key]=directory;
}
process.env.CI="true";process.env.FIREBASE_CLI_DISABLE_UPDATE_CHECK="true";

const exec=cp.execFileSync;cp.execFileSync=(file,args,options)=>{assert.match(String(file),/(?:^|[\\/])git(?:\.exe)?$/i);const at=Date.now();fs.appendFileSync(path.join(out,"git-observations.jsonl"),JSON.stringify({event:"start",at,arguments:args})+"\n");try{return exec(file,args,{...options,timeout:Math.min(options?.timeout??30000,30000)});}finally{fs.appendFileSync(path.join(out,"git-observations.jsonl"),JSON.stringify({event:"end",elapsedMs:Date.now()-at})+"\n");}};for(const n of ["spawn","spawnSync","exec","execSync","execFile","fork"])cp[n]=()=>{throw Error("NON-GIT CHILD FORBIDDEN");};
// No external transport or non-Git child is possible in this harness.
require("node:net").Socket.prototype.connect=()=>{throw Error("REAL SOCKET FORBIDDEN");};require("node:tls").connect=()=>{throw Error("REAL TLS FORBIDDEN");};globalThis.fetch=()=>{throw Error("REAL FETCH FORBIDDEN");};
const BASE=require("./business31CaptureFixture.cjs").createCaptureFixture31(out);
const hookModule=require("./captureBusiness31PreparedHook.cjs"),{BusinessCapture31}=require("./captureBusiness31PreparedInputs.cjs"),neutral=require("./backendRuntimeClosure31.cjs");
const x=require("./business31ExecutionContract.cjs");
const hash=b=>crypto.createHash("sha256").update(b).digest("hex").toUpperCase(),cohorts=x.cohortsFromPolicy(JSON.parse(fs.readFileSync(path.join(root,"release/function-fleet-runtime-identity-policy.json"))));
const boundCli=require("./business31CaptureFixture.cjs").createBoundCliFixture31(root,out),cli=boundCli.cli,runtime={...boundCli.runtime,instrumentationProducerSha256:Object.fromEntries(Object.entries({api:"apiv2.js",apply:"deploy/functions/cache/applyHash.js",prepare:"deploy/functions/prepare.js",backend:"deploy/functions/backend.js"}).map(([k,p])=>[k,hash(fs.readFileSync(path.join(cli,p)))])),endpointHashProducerSha256:Object.fromEntries(Object.entries({apply:"deploy/functions/cache/applyHash.js",hash:"deploy/functions/cache/hash.js",secrets:"functions/secrets.js"}).map(([k,p])=>[k,hash(fs.readFileSync(path.join(cli,p)))]))};
const auth=require(path.join(cli,"auth.js"));auth.getAccessToken=auth.haveValidTokens=()=>{throw Error("CREDENTIAL ACCESS FORBIDDEN");};


function fixture(editDecision) {
 const dir=fs.mkdtempSync(path.join(out,"fixture-")),evidence=path.join(dir,"evidence");fs.mkdirSync(evidence);
 const archive=path.join(dir,"original-source.zip");fs.copyFileSync(BASE.archive,archive);
 const retain=(name,value)=>{const b=Buffer.from(JSON.stringify(value,null,2)+"\n");fs.writeFileSync(path.join(evidence,name),b,{flag:"wx"});return {file:name,sha256:hash(b),bytes:b.length};};
 const checked=neutral.verifyArchiveBytes31(fs.readFileSync(archive),BASE.archiveExpectedFiles),now=Date.now(),T=d=>new Date(now+d).toISOString();
 const env={GCLOUD_PROJECT:"crm3-baf-ops-b8638",FIREBASE_CONFIG:'{"projectId":"crm3-baf-ops-b8638"}',CRM3_MUTATING_CALLABLE_ENFORCE_APP_CHECK:"false",CRM3_INSPECTION_READING_V2_AUTHORING_ENABLED:"false"};
 const endpoints=Object.fromEntries(cohorts.fleet.map(id=>[id,{id,platform:"gcfv2",project:"crm3-baf-ops-b8638",region:"asia-south1",secretEnvironmentVariables:[{key:"SYNTHETIC_CONFIG",secret:"synthetic-name",projectId:"crm3-baf-ops-b8638",version:"1"},{key:"SYNTHETIC_SECOND",secret:"second-name",projectId:"crm3-baf-ops-b8638",version:"2"}]}]));
 const intent={schemaVersion:1,documentType:"firebase-cli-approved-intended-hash-inputs",codebase:"default",source:BASE.source,sourceBefore:BASE.source,sourceAfter:BASE.source,sourceArchiveHash:checked.sourceArchiveHash,startedAtUtc:T(-4000),completedAtUtc:T(-3000),environmentVariables:env,endpoints};
 const intentPointer=retain("intent.json",intent),proof=retain("runtime-proof.json",{syntheticLocalFixture:true}),contract={schemaVersion:1,documentType:"build31-business-execution-contract",profile:"build31-exact-business-backend-v1",source:BASE.source,sourceManifestSha256:"A".repeat(64),runtimeProof:proof,preparedAtUtc:T(-2000),intendedHashInputs:intentPointer};
 const contractPointer=retain("execution-contract.json",contract),decision={schemaVersion:2,documentType:"build31-business-backend-deployment-decision",profile:contract.profile,source:BASE.source,sourceManifestSha256:contract.sourceManifestSha256,runtimeProof:proof,decidedAtUtc:T(-1000),executionWindow:{notBeforeUtc:T(-500),notAfterUtc:T(3600000)},executionContract:contractPointer};if(editDecision)editDecision(decision);
 const dp=retain("decision.json",decision),envelopeBytes=Buffer.from(JSON.stringify({schemaVersion:1,documentType:"build31-business-private-record-custody",recordKind:"decision",source:BASE.source,privateRecord:dp}));
 const approvalPointer={commit:"c".repeat(40),file:"release/approvals/build31-business-backend-deployment-approval.json",sha256:hash(envelopeBytes)},writer=new BusinessCapture31({evidenceDirectory:evidence,source:BASE.source,approvalPointer,cohorts});
 const admission={repoRoot:BASE.repository,source:BASE.source,approvalPointer,cohorts,projectId:"crm3-baf-ops-b8638",region:"asia-south1",runtime};
 const wantBackends={default:{environmentVariables:structuredClone(env),endpoints:{"asia-south1":structuredClone(endpoints)}}},context={sources:{default:{functionsSourceV2:archive,functionsSourceV2Hash:checked.sourceArchiveHash}}};
 return {dir,evidence,archive,envelopeBytes,writer,admission,wantBackends,context,intent,options:{writer,phase:"callables",admission,envelopeBytes,archiveExpectedFiles:BASE.archiveExpectedFiles,guardInputs:{baselineFunctions:{},projectNumber:"123456789"}}};
}
test("actual installed apply/hash output joins real local Git, strict ZIP, ordered intent and retained path",()=>{const f=fixture(),before=JSON.stringify(f.context),hook=hookModule.installBusinessPreparedHook31(f.options);try{const returned=hook.module.applyBackendHashToBackends(f.wantBackends,f.context);assert.equal(returned,undefined);const result=hook.getResult();assert.equal(result.hashFunctionReturnType,"undefined");assert.equal(result.originalArchivePath,f.archive);assert.notEqual(result.retainedArchivePath,f.archive);assert.equal(fs.readFileSync(result.retainedArchivePath).equals(fs.readFileSync(f.archive)),true);assert.equal(result.archiveSha256,BASE.archiveSha256);assert.equal(f.context.sources.default.functionsSourceV2,result.retainedArchivePath);assert.equal(JSON.parse(before).sources.default.functionsSourceV2,f.archive);assert.equal(f.context.sources.default.functionsSourceV2Hash,f.intent.sourceArchiveHash);const capture=JSON.parse(fs.readFileSync(path.join(f.evidence,result.capture.file)));assert.deepEqual(Object.keys(capture.endpoints),cohorts.fleet);assert.equal(JSON.stringify(capture.environmentVariables),JSON.stringify(f.intent.environmentVariables));assert.deepEqual(capture.source,BASE.source);assert.equal(Object.keys(capture.endpointRuntimeHashes).length,19);for(const n of cohorts.fleet)assert.equal(f.wantBackends.default.endpoints['asia-south1'][n].hash,capture.endpointRuntimeHashes[n]);assert.equal(result.fullFirebasePrepareCalled,false);assert.equal(result.authenticatedDecision,false);fs.writeFileSync(path.join(f.dir,"TEST_RESULT.json"),JSON.stringify(result,null,2));}finally{hook.restore();}});
test("schema1 decision refuses before hooking real module",()=>{const f=fixture(d=>d.schemaVersion=1);assert.throws(()=>hookModule.installBusinessPreparedHook31(f.options),/schema2/);assert.equal(f.writer.active,null);});
test("changed public custody bytes refuse",()=>{const f=fixture();f.options.envelopeBytes=Buffer.concat([f.envelopeBytes,Buffer.from(" ")]);assert.throws(()=>hookModule.installBusinessPreparedHook31(f.options),/custody/);});
test("changed private intent pointer bytes refuse",()=>{const f=fixture();fs.appendFileSync(path.join(f.evidence,"intent.json")," ");assert.throws(()=>hookModule.installBusinessPreparedHook31(f.options),/private/);});
test("same environment properties in different order refuse without selecting new ZIP",()=>{const f=fixture(),hook=hookModule.installBusinessPreparedHook31(f.options);try{f.wantBackends.default.environmentVariables=Object.fromEntries(Object.entries(f.intent.environmentVariables).reverse());assert.throws(()=>hook.module.applyBackendHashToBackends(f.wantBackends,f.context),/ordered/);assert.equal(f.context.sources.default.functionsSourceV2,f.archive);assert.equal(hook.state(),"failed");assert.ok(fs.existsSync(path.join(f.writer.base,"prepared-hook-callables/failed.json")));assert.throws(()=>hook.module.applyBackendHashToBackends(f.wantBackends,f.context),/retry twice/);}finally{hook.restore();}});
test("resolved secret metadata order and version cannot drift",()=>{for(const kind of ["order","version"]){const f=fixture(),hook=hookModule.installBusinessPreparedHook31(f.options);try{const row=f.wantBackends.default.endpoints['asia-south1'][cohorts.fleet[0]].secretEnvironmentVariables;if(kind==="order")row.reverse();else row[0].version="3";assert.throws(()=>hook.module.applyBackendHashToBackends(f.wantBackends,f.context),/secret versions/);assert.equal(f.context.sources.default.functionsSourceV2,f.archive);}finally{hook.restore();}}});
test("missing endpoint refuses complete19 capture",()=>{const f=fixture(),hook=hookModule.installBusinessPreparedHook31(f.options);try{delete f.wantBackends.default.endpoints['asia-south1'][cohorts.fleet[0]];assert.throws(()=>hook.module.applyBackendHashToBackends(f.wantBackends,f.context),/endpoint population/);assert.equal(f.writer.active,null);}finally{hook.restore();}});
test("changed original ZIP fails real CRC/member validation",()=>{const f=fixture(),hook=hookModule.installBusinessPreparedHook31(f.options);try{const b=fs.readFileSync(f.archive);b[60]^=1;fs.writeFileSync(f.archive,b);assert.throws(()=>hook.module.applyBackendHashToBackends(f.wantBackends,f.context));assert.equal(f.context.sources.default.functionsSourceV2,f.archive);assert.equal(f.writer.active,null);}finally{hook.restore();}});
test("wrong installed producer digest refuses before hash module hook",()=>{const f=fixture();f.options.admission={...f.admission,runtime:{...runtime,instrumentationProducerSha256:{...runtime.instrumentationProducerSha256,apply:"F".repeat(64)}}};assert.throws(()=>hookModule.installBusinessPreparedHook31(f.options),/instrumentation/);});
test("second invocation cannot rewrite a captured preparation",()=>{const f=fixture(),hook=hookModule.installBusinessPreparedHook31(f.options);try{hook.module.applyBackendHashToBackends(f.wantBackends,f.context);const original=hook.getResult();assert.throws(()=>hook.module.applyBackendHashToBackends(f.wantBackends,f.context),/retry twice/);assert.deepEqual(hook.getResult(),original);}finally{hook.restore();}});
test("hook restoration refuses to overwrite another hook owner",()=>{const f=fixture(),hook=hookModule.installBusinessPreparedHook31(f.options),wrapper=hook.module.applyBackendHashToBackends,foreign=()=>{};hook.module.applyBackendHashToBackends=foreign;assert.throws(()=>hook.restore(),/ownership/);assert.equal(hook.module.applyBackendHashToBackends,foreign);hook.module.applyBackendHashToBackends=wrapper;hook.restore();});
test.after(()=>{const files={};for(const p of Object.keys(require.cache))if(p.startsWith(path.dirname(cli)+path.sep)||p.startsWith(path.dirname(path.dirname(cli))+path.sep))files[path.relative(path.dirname(path.dirname(cli)),p).split(path.sep).join('/')]=hash(fs.readFileSync(p));assert.equal(Object.keys(files).some(p=>p.endsWith('/prepare.js')),false);assert.equal(Object.keys(files).some(p=>p.endsWith('/bin/firebase.js')),false);fs.writeFileSync(path.join(out,"INSTALLED_MODULE_BINDINGS.json"),JSON.stringify({files,prepareLoaded:false,deployEntryLoaded:false,authFunctionsInvoked:false},null,2));});

test.after(()=>{try{boundCli.assertOriginalUnchanged();}finally{boundCli.lease.release();}});

}
