'use strict';
// PRIVATE preflight facade. Deliberately cannot satisfy a production release gate.
const path=require('./backendRuntimeEvidenceAccess31.cjs').path;
const a=require('./backendRuntimeAdmission31.cjs');
const {need,eq,time,committed,ancestor,git,hash}=a.helpers;
function verifyClientRuntimeCompatibility31Inner({repoRoot,authorityRoot,releasePolicy,version,evidenceDirectory,nowUtc=new Date().toISOString()}){
 const pointer=releasePolicy?.clientBackendCompatibility;need(pointer?.file===a.PATHS.client,'Distinct runtime compatibility pointer required');eq(pointer,version?.requiredSource?.clientBackendCompatibility,'Policy and version custody differ');need(releasePolicy.release?.buildNumber===31&&releasePolicy.versionPolicy?.buildNumber===31,'Only bounded generation31 admitted');
 const decision=committed(authorityRoot,pointer,a.PATHS.client);need(decision.schemaVersion===2&&decision.documentType==='build31-client-new-runtime-backend-compatibility-decision'&&decision.approved===true,'Separate exact client decision required');
 eq(decision.scope,{clientConstructionOnly:true,backendDeploymentAuthorized:false,distributionAuthorized:false,iamOrEnforcementChangeAuthorized:false},'Client decision cannot authorize deployment/distribution');
 const closure=require('./backendRuntimeClosure31.cjs').verifyBackendRuntimeClosure31({repoRoot,authorityRoot,approvalPointer:decision.backendApprovalPointer,closurePointer:decision.backendClosurePointer,evidenceDirectory,nowUtc});eq(decision.source,closure.source,'Client source differs from actually deployed M');ancestor(authorityRoot,decision.backendClosurePointer.commit,pointer.commit);a.helpers.verifyCustodyDelta(authorityRoot,closure.source.commit,pointer.commit);
 need(time(closure.recordedAtUtc)<=time(decision.decidedAtUtc)&&time(decision.decidedAtUtc)<=time(decision.recordedAtUtc)&&time(decision.recordedAtUtc)<=time(nowUtc),'Client decision must follow actual closure');const custody=BigInt(a.helpers.gtext(authorityRoot,['show','-s','--format=%ct',pointer.commit]))*1000000000n;need(time(decision.recordedAtUtc)<custody+1000000000n&&custody<=time(nowUtc),'Client decision was not committed after its observations');
 need(releasePolicy.appCheckBuild?.clientEnabled===true&&releasePolicy.appCheckBuild?.androidProvider==='playIntegrity','Build31 still requires enabled Play Integrity');
 need(decision.ownerAuthorization?.file==='release/approvals/build31-runtime-client-owner-authorization.json','Separate source-specific client owner record required');const owner=a.helpers.child(authorityRoot,pointer.commit,decision.ownerAuthorization,decision.ownerAuthorization.file);need(owner.approved===true&&owner.documentType==='build31-exact-source-client-owner-authorization'&&owner.ownerReference===decision.ownerReference&&typeof owner.ownerInstruction==='string'&&owner.ownerInstruction.trim().length>20,'Actual client owner authorization required');eq(owner.source,decision.source,'Client owner source differs');eq(owner.scope,decision.scope,'Client owner scope differs');need(time(owner.authorizedAtUtc)>=time(closure.recordedAtUtc)&&time(owner.authorizedAtUtc)<=time(owner.recordedAtUtc)&&time(owner.recordedAtUtc)<=time(decision.decidedAtUtc),'Client owner chronology differs');
 return {ok:true,proposalOnly:true,deploymentAuthorized:false,constructionAuthority:false,distributionAuthorized:false,source:closure.source,backendClosurePointer:decision.backendClosurePointer,clientDecisionPointer:pointer,activationBlocked:true};
}
function inspectClientAuthorityRoute31(releasePolicy){const pointer=releasePolicy?.clientBackendCompatibility;if(pointer?.file===a.PATHS.client)return {route:'runtime-backend31',activationBlocked:true};return {route:'existing-exact-or-development-only',activationBlocked:false};}
function verifyProposedClientAuthorityFacade31(args){
 if(inspectClientAuthorityRoute31(args.releasePolicy).route!=='runtime-backend31')return require(path.join(args.repoRoot,'tools/release/clientBackendCompatibility31.js')).verifyClientBackendSourceAuthority(args);
 try{const proof=verifyClientRuntimeCompatibility31(args);return {ok:false,constructionAuthority:false,reasons:['Private runtime preflight passed; production activation and authoritative entrypoint integration remain unapproved.'],proposal:proof};}catch(error){return {ok:false,constructionAuthority:false,reasons:[error.message]};}
}
function verifyClientRuntimeCompatibility31(config){return require('./backendRuntimeEvidenceAccess31.cjs').runEvidence31(config,()=>verifyClientRuntimeCompatibility31Inner(config));}
module.exports={verifyClientRuntimeCompatibility31,inspectClientAuthorityRoute31,verifyProposedClientAuthorityFacade31};
