'use strict';
const assert=require('node:assert/strict'),test=require('node:test'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {validateMeasured,validateExactMainCiPair,collectRuntimeProof,PLAN,inventory,sourceInventory,runtimeInputs,verifyInstalledAgainstLock,expectedEmittedFiles,assertExportPreserved,recordCommandRun,measureToolPackage}=require('./collectClientBuildToolingRuntime31.cjs');
const {fixture,reseal,byteRecord,installedFixtureFromLock}=require('./clientBuildToolingRuntime31.synthetic-fixture.cjs');
function check(f){return validateMeasured(f.receipt,f.context);}
test('synthetic complete measured receipt validates only as corroboration',()=>{const f=fixture();assert.deepEqual(check(f),{ok:true,emittedFileCount:2,constructionAuthority:false});});
const negatives=[
 ['wrong schema',f=>f.receipt.schemaVersion=true],['unknown top field',f=>f.receipt.unreviewed=true],['missing commands',f=>delete f.receipt.commands],
 ['wrong generation',f=>f.receipt.boundary.generation=32],['construction flag',f=>f.receipt.boundary.constructionAuthority=true],['scope field added',f=>f.receipt.boundary.ownerApproved=true],
 ['wrong source',f=>f.receipt.candidateCommit='c'.repeat(40)],['wrong deployedF',f=>f.receipt.baselineCommit='d'.repeat(40)],['wrong literal branch',f=>f.receipt.sourceBefore.branch='codex/test'],['dirty source',f=>f.receipt.sourceAfter.clean=false],
 ['producer substituted',f=>f.receipt.producerHashes={unknown:'B'.repeat(64)}],['CI substituted',f=>f.receipt.ciHashes.release='B'.repeat(64)],['exported file omitted',f=>f.receipt.exportedSources.baseline=[]],
 ['one command omitted',f=>f.receipt.commands.pop()],['extra command',f=>f.receipt.commands.push(f.receipt.commands[0])],['altered argv',f=>f.receipt.commands[2].args=['deploy']],['wrong role',f=>f.receipt.commands[2].role='production'],
 ['failed command',f=>f.receipt.commands[2].exitCode=1],['boolean exit',f=>f.receipt.commands[2].exitCode=false],['missing structured JSON',f=>f.receipt.commands[8].structuredResult=null],
 ['structured bytes forged',f=>f.receipt.commands[8].stdout.sha256='B'.repeat(64)],['tool text forged',f=>f.receipt.commands[0].stdoutText='v22.99.0\n'],
 ['missing stderr hash',f=>delete f.receipt.commands[2].stderr.sha256],['extra command field',f=>f.receipt.commands[2].skip=true],['preCI capture',f=>f.receipt.startedAtUtc=f.releaseCi.run.created_at],
 ['future completion',f=>f.receipt.completedAtUtc=new Date(Date.now()+60000).toISOString()],['reversed command times',f=>f.receipt.commands[2].completedAtUtc=f.receipt.startedAtUtc],
 ['wrongNode',f=>f.receipt.tools.node.version='v24.0.0'],['compiler drift',f=>f.receipt.tools.candidateCompiler.sha256='B'.repeat(64)],['compiler tool field omitted',f=>delete f.receipt.tools.npm],
 ['emitted output omitted',f=>delete f.receipt.emitted.candidate['index.js.map']],['emitted bytes differ',f=>f.receipt.emitted.candidate['index.js'].bytes=2],['unsafe output path',f=>f.receipt.emitted.baseline['../outside.js']={sha256:'A'.repeat(64),bytes:1}],
 ['installed runtime changed',f=>f.receipt.installed.candidate.dependencies.extra={version:'1'}],['audit population absent',f=>delete f.receipt.audits['cli-full']],
 ['audit warning added',f=>f.receipt.audits['root-full'].vulnerabilities.unsafe={severity:'high'}],['boolean audit0',f=>f.receipt.audits['functions-full'].metadata.vulnerabilities.total=false],
];
for(const[name,mutate]of negatives)test('rejects '+name,()=>{const f=fixture();mutate(f);f.receipt=reseal(f.receipt);assert.throws(()=>check(f));});
test('seal is required before replay',()=>{const f=fixture();f.receipt.startedAtUtc=f.receipt.completedAtUtc;assert.throws(()=>check(f),/seal/);});
test('nanosecond future command beyond its capture is rejected',()=>{const f=fixture();f.receipt.commands.at(-1).completedAtUtc=f.receipt.completedAtUtc.replace('Z','000001Z');f.receipt=reseal(f.receipt);assert.throws(()=>check(f),/chronology/);});
test('compiler report source population cannot be shortened equally',()=>{const f=fixture();for(const c of f.receipt.commands.filter(c=>c.id.endsWith('-emitted'))){c.structuredResult.sourceCount=2;c.stdoutText=JSON.stringify(c.structuredResult);c.stdout=byteRecord(c.stdoutText);}f.receipt=reseal(f.receipt);assert.throws(()=>check(f),/source population/);});
test('rebound actual audit error still fails',()=>{const f=fixture();const c=f.receipt.commands.find(c=>c.id==='root-full');c.structuredResult.error={code:'EUNAVAILABLE'};c.stdoutText=JSON.stringify(c.structuredResult);c.stdout=byteRecord(c.stdoutText);f.receipt.audits['root-full']=structuredClone(c.structuredResult);f.receipt=reseal(f.receipt);assert.throws(()=>check(f),/clean actual audit/);});
test('fixed command plan cannot be changed by importer',()=>{assert.throws(()=>{PLAN[2][3][0]='deploy';},TypeError);assert.throws(()=>{PLAN[2][1]='production';},TypeError);});
test('both exact CI populations required',()=>{const f=fixture();assert.ok(validateExactMainCiPair({candidateCommit:f.context.candidateCommit,sourceTree:f.context.tree,releaseCi:f.releaseCi,securityCi:f.securityCi}).lastCompletionUtc);});
for(const[name,mutate]of [
 ['PR rather than main',f=>f.releaseCi.run.event='pull_request'],['missing host job',f=>f.releaseCi.jobs.jobs.pop()],['security failed',f=>f.securityCi.jobs.jobs[0].conclusion='failure'],['duplicate job',f=>f.securityCi.jobs.jobs[1].id=f.securityCi.jobs.jobs[0].id],['wrong main tree',f=>f.releaseCi.sourceTree='c'.repeat(40)],['boolean run id',f=>f.releaseCi.run.id=true],['future capture',f=>f.securityCi.capturedAtUtc=new Date(Date.now()+1000).toISOString()]
])test('CI guard rejects '+name,()=>{const f=fixture();mutate(f);assert.throws(()=>validateExactMainCiPair({candidateCommit:f.context.candidateCommit,sourceTree:f.context.tree,releaseCi:f.releaseCi,securityCi:f.securityCi}));});
test('collector rejects source before any output or network on current unmerged private checkout',()=>{const primary=require('node:child_process').execFileSync('git',['-C',__dirname,'rev-parse','--show-toplevel'],{encoding:'utf8',windowsHide:true}).trim();const output=path.join(os.tmpdir(),'crm3-runtime-proof-not-created-'+process.pid);assert.equal(fs.existsSync(output),false);assert.throws(()=>collectRuntimeProof({repoRoot:primary,candidateCommit:'0'.repeat(40),releaseCiFile:'absent',securityCiFile:'absent',outputDirectory:output}));assert.equal(fs.existsSync(output),false);});
test('emitted inventory rejects unexpected output type and preserves evidence',()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'crm3-proof-inventory-'));fs.writeFileSync(path.join(d,'index.js'),'x');fs.writeFileSync(path.join(d,'index.js.map'),'y');assert.equal(Object.keys(inventory(d)).length,2);fs.writeFileSync(path.join(d,'unexpected.txt'),'z');assert.throws(()=>inventory(d),/Unexpected emitted/);assert.equal(fs.existsSync(path.join(d,'unexpected.txt')),true);});

for(const field of ['run','job'])for(const [label,value]of [['false',false],['string','1'],['zero',0],['missing',undefined]])test('CI '+field+' attempt rejects '+label,()=>{const f=fixture();const target=field==='run'?f.releaseCi.run:f.releaseCi.jobs.jobs[0];if(value===undefined)delete target.run_attempt;else target.run_attempt=value;assert.throws(()=>validateExactMainCiPair({candidateCommit:f.context.candidateCommit,sourceTree:f.context.tree,releaseCi:f.releaseCi,securityCi:f.securityCi}));});
test('CI attempts cannot mix successful jobs from old attempt',()=>{const f=fixture();f.securityCi.run.run_attempt=2;assert.throws(()=>validateExactMainCiPair({candidateCommit:f.context.candidateCommit,sourceTree:f.context.tree,releaseCi:f.releaseCi,securityCi:f.securityCi}));});
test('same-sized invented emitted names fail independently derived source population',()=>{const f=fixture();f.context.sourceInventories.baseline.push({path:'functions/src/real.ts',mode:'100644',blob:'c'.repeat(40),sha256:'A'.repeat(64),bytes:1});f.context.sourceInventories.candidate=structuredClone(f.context.sourceInventories.baseline);f.receipt.exportedSources=structuredClone(f.context.sourceInventories);for(const side of ['baseline','candidate']){f.receipt.emitted[side]['invented.js']={sha256:'A'.repeat(64),bytes:1};f.receipt.emitted[side]['invented.js.map']={sha256:'A'.repeat(64),bytes:1};const c=f.receipt.commands.find(c=>c.id===side+'-emitted');c.structuredResult={sourceCount:2,expectedFiles:Object.keys(f.receipt.emitted[side]).sort(),actualFiles:Object.keys(f.receipt.emitted[side]).sort()};c.stdoutText=JSON.stringify(c.structuredResult);c.stdout=byteRecord(c.stdoutText);}f.receipt=reseal(f.receipt);assert.throws(()=>check(f),/immutable Git/);});
test('required runtime package cannot be omitted equally',()=>{const f=fixture();for(const side of ['baseline','candidate']){f.context.runtimeInputs[side].manifest.dependencies.second='1';f.context.runtimeInputs[side].lock.packages['node_modules/second']={version:'1'};}assert.throws(()=>check(f),/Required runtime/);});
function dependencyFixture(){return {manifest:{name:'fixture',dependencies:{a:'1'}},lock:{packages:{'node_modules/a':{version:'1',dependencies:{b:'2'}},'node_modules/b':{version:'2'}}}};}
test('synthetic graph represents complete required and deduplicated runtime lock',()=>{const x=dependencyFixture();x.manifest.dependencies.b='2';const graph=installedFixtureFromLock(x.manifest,x.lock);assert.equal(verifyInstalledAgainstLock({...x,graph}).runtimeInstalledPaths,2);});
for(const[name,mutate]of [
 ['missing child',g=>delete g.dependencies.a.dependencies],['wrong child version',g=>g.dependencies.a.dependencies.b.version='3'],['unexpected development node',g=>g.dependencies.dev={version:'1'}],['empty required child',g=>g.dependencies.a.dependencies.b={}],['problems flag',g=>g.dependencies.a.problems=[]]
])test('runtime graph rejects '+name,()=>{const x=dependencyFixture(),graph=installedFixtureFromLock(x.manifest,x.lock);mutate(graph);assert.throws(()=>verifyInstalledAgainstLock({...x,graph}));});
test('optional absent node is allowed without relaxing required descendants',()=>{const x=dependencyFixture();x.lock.packages['node_modules/a'].optionalDependencies={optional:'3'};x.lock.packages['node_modules/optional']={version:'3',optional:true};const graph=installedFixtureFromLock(x.manifest,x.lock);graph.dependencies.a.dependencies.optional={};assert.equal(verifyInstalledAgainstLock({...x,graph}).runtimeInstalledPaths,2);});
test('nonoptional peer is required and optional peer may be absent',()=>{const x=dependencyFixture();x.lock.packages['node_modules/a'].peerDependencies={peer:'4'};x.lock.packages['node_modules/peer']={version:'4'};let graph=installedFixtureFromLock(x.manifest,x.lock);delete graph.dependencies.a.dependencies.peer;assert.throws(()=>verifyInstalledAgainstLock({...x,graph}),/Required runtime/);x.lock.packages['node_modules/a'].peerDependenciesMeta={peer:{optional:true}};assert.equal(verifyInstalledAgainstLock({...x,graph}).runtimeInstalledPaths,2);});
test('failed JSON command preserves raw logs and exit status before parse',()=>{const output=fs.mkdtempSync(path.join(os.tmpdir(),'crm3-proof-failed-')),logs=path.join(output,'logs');fs.mkdirSync(logs);const commands=[],entry=PLAN.find(x=>x[0]==='root-full');assert.throws(()=>recordCommandRun({run:{status:1,stdout:Buffer.from('NOT JSON'),stderr:Buffer.from('registry failed')},entry,startedAtUtc:new Date().toISOString(),completedAtUtc:new Date().toISOString(),logs,outputDirectory:output,commands}),/Fixed command failed/);const saved=JSON.parse(fs.readFileSync(path.join(output,'commands-progress.json')));assert.equal(saved[0].exitCode,1);assert.equal(fs.readFileSync(path.join(logs,'root-full.stdout.log'),'utf8'),'NOT JSON');});
test('exported file bytes and parent junction remain guarded',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'crm3-proof-export-')),dir=path.join(root,'src');fs.mkdirSync(dir);fs.writeFileSync(path.join(dir,'index.ts'),'actual');const rows=[{path:'src/index.ts',mode:'100644',...byteRecord('actual')}];assert.equal(assertExportPreserved(root,rows),true);fs.renameSync(dir,path.join(root,'retained-src'));fs.symlinkSync(path.join(root,'retained-src'),dir,'junction');assert.throws(()=>assertExportPreserved(root,rows),/reparse/);});
test('read-only actual deployed Git inventory has independently derived248 outputs and synthetic252-path graph',()=>{const primary=require('node:child_process').execFileSync('git',['-C',__dirname,'rev-parse','--show-toplevel'],{encoding:'utf8',windowsHide:true}).trim(),f='2aa30de56cfdb960da3eeefd8956d8cbbae57b46',sources=sourceInventory(primary,f),inputs=runtimeInputs(primary,f);assert.equal(expectedEmittedFiles(sources).length,248);assert.equal(verifyInstalledAgainstLock({...inputs,graph:installedFixtureFromLock(inputs.manifest,inputs.lock)}).runtimeInstalledPaths,252);});

test('full npm package measurement detects changed dependency behind unchanged CLI stub',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'crm3-proof-npm-'));fs.writeFileSync(path.join(root,'package.json'),JSON.stringify({name:'npm',version:'10.9.2'}));fs.mkdirSync(path.join(root,'bin'));fs.writeFileSync(path.join(root,'bin','npm-cli.js'),'same cli');fs.mkdirSync(path.join(root,'lib'));fs.writeFileSync(path.join(root,'lib','dependency.js'),'before');const before=measureToolPackage(root,'npm');fs.writeFileSync(path.join(root,'lib','dependency.js'),'after');assert.notEqual(measureToolPackage(root,'npm').sha256,before.sha256);assert.throws(()=>measureToolPackage(root,'typescript'),/identity/);});
