"use strict";
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawnSync,execFileSync}=require('node:child_process');
const {retainCommandResult}=require('./collectClientDevelopmentToolIam31.cjs');
const {verifyWrappingCode,WRAPPING_PRODUCERS}=require('./clientBuildToolingReadbacks31.cjs');
const candidate=path.resolve(__dirname,'../..'),parent=os.tmpdir();
test('successful local command retains actual stdout and stderr warnings',()=>{const dir=fs.mkdtempSync(path.join(parent,'iam-stderr-positive-'));const result=spawnSync(process.execPath,['-e','process.stdout.write("normal output\\n");process.stderr.write("actual warning\\n")'],{encoding:null});const record=retainCommandResult(dir,{startedAtUtc:new Date().toISOString()},result);assert.equal(record.exitCode,0);assert.equal(fs.readFileSync(path.join(dir,'stderr.log'),'utf8'),'actual warning\n');assert.equal(fs.readFileSync(path.join(dir,'stdout.log'),'utf8'),'normal output\n');assert.equal(record.stderr.bytes,Buffer.byteLength('actual warning\n'));});
test('failed local command retains real stderr status and stdout',()=>{const dir=fs.mkdtempSync(path.join(parent,'iam-stderr-failure-'));const result=spawnSync(process.execPath,['-e','process.stdout.write("partial");process.stderr.write("failure");process.exit(7)'],{encoding:null});const record=retainCommandResult(dir,{startedAtUtc:new Date().toISOString()},result);assert.equal(record.exitCode,7);assert.equal(fs.readFileSync(path.join(dir,'stderr.log'),'utf8'),'failure');assert.equal(fs.readFileSync(path.join(dir,'stdout.log'),'utf8'),'partial');});
test('timeout/null status and signal are retained instead of successful exit',()=>{const dir=fs.mkdtempSync(path.join(parent,'iam-timeout-retained-'));const record=retainCommandResult(dir,{}, {status:null,signal:'SIGTERM',error:new Error('timeout'),stdout:Buffer.from('partial'),stderr:Buffer.from('warning')});assert.equal(record.exitCode,null);assert.equal(record.signal,'SIGTERM');assert.match(record.error,/timeout/);});
test('executing wrapper mismatch fails immutable producer preflight',()=>{const dir=fs.mkdtempSync(path.join(parent,'iam-wrapper-source-negative-'));const env={...process.env,GIT_AUTHOR_NAME:'Synthetic fixture',GIT_AUTHOR_EMAIL:'fixture@example.invalid',GIT_COMMITTER_NAME:'Synthetic fixture',GIT_COMMITTER_EMAIL:'fixture@example.invalid'};const git=(...args)=>execFileSync('git',['--no-replace-objects','-C',dir,...args],{env,encoding:'utf8',windowsHide:true}).trim();git('init','--quiet');for(const file of WRAPPING_PRODUCERS){const target=path.join(dir,file);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,fs.readFileSync(path.join(candidate,file)));}fs.appendFileSync(path.join(dir,WRAPPING_PRODUCERS[0]),'\n// synthetic altered wrapper\n');git('add','.');git('commit','--quiet','-m','Synthetic altered-wrapper fixture; no authority');assert.throws(()=>verifyWrappingCode(dir,git('rev-parse','HEAD')),/Executing wrapper\/helper differs.*collectClientDevelopmentToolIam31/);});
