'use strict';
const fs=require('node:fs'),path=require('node:path'),{spawnSync}=require('node:child_process');
const a=require('./backendRuntimeAdmission31.cjs'),e=require('./backendRuntimeExecutionAdmission31.cjs');
const {need,eq,hash,object,time}=a.helpers;
const {exactPhaseDirectory,privateBinding}=require('./captureBackendRuntimePreparedInputs31.cjs');
const PHASES=['callables','events','fleet'];
function validateConfig(config){eq(Object.keys(config??{}).sort(),['repoRoot','authorityRoot','evidenceDirectory','approvalPointer','phase'].sort(),'Only fixed deployment inputs are allowed');need(PHASES.includes(config.phase),'Unknown deployment phase');return config;}
function phaseNames(admission,phase){return phase==='fleet'?admission.cohorts.schedulers:admission.cohorts[phase];}
function snapshot(admission){need(a.helpers.gtext(admission.repoRoot,['branch','--show-current'])==='main'&&a.helpers.gtext(admission.repoRoot,['rev-parse','HEAD'])===admission.source.commit&&a.helpers.gtext(admission.repoRoot,['rev-parse','refs/remotes/origin/main'])===admission.source.commit&&a.helpers.gtext(admission.repoRoot,['status','--porcelain','--untracked-files=normal'])==='','Exact clean execution main changed');return {...admission.source,branch:'main',originMain:admission.source.commit,liveMain:admission.source.commit,clean:true};}
function append(file,data){fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n',{flag:'wx',mode:0o600});}
function verifyPriorPhases31(admission,phase){for(const p of PHASES.slice(0,PHASES.indexOf(phase))){const dir=exactPhaseDirectory(admission,p),r=object(fs.readFileSync(path.join(dir,'attempt-result.json')));need(r.schemaVersion===2&&r.exitCode===0&&r.actualDeploymentPerformed===true&&r.phase===p&&r.attempt===1&&!r.signal&&!r.error,'Earlier cohort is incomplete/failed; retry is not automatic');eq(r.source,admission.source,'Prior cohort source differs');eq(r.approvalPointer,admission.approvalPointer,'Prior cohort approval differs');eq(r.functions,phaseNames(admission,p),'Prior exact cohort differs');for(const key of ['stdout','stderr','capture','archive','instrumentedCompletion'])a.helpers.fileBinding(admission.evidenceDirectory,r[key]);need(time(r.completedAtUtc)<=time(new Date().toISOString()),'Prior cohort completion lies in future');}}
function planBackendRuntimeExecution31(config){validateConfig(config);const {phase,...base}=config,admission=a.verifyBackendRuntimeAdmission31({...base,requireExecutionHead:false});return {ok:true,actualDeploymentPerformed:false,deploymentAuthorized:false,source:admission.source,phase,functions:phaseNames(admission,phase),requiresSeparateActualOwnerDeploymentDecision:true,automaticRetryAllowed:false};}
function executeBackendRuntime31(config){
  validateConfig(config);const {phase,...base}=config,admission=e.verifyBackendRuntimeExecutionAdmission31(base);verifyPriorPhases31(admission,phase);
  const sourceBefore=snapshot(admission),directory=exactPhaseDirectory(admission,phase);need(!fs.existsSync(directory),'An attempt already exists; preserve it and obtain an explicit new decision, never retry automatically');
  fs.mkdirSync(path.dirname(directory),{recursive:true});fs.mkdirSync(directory);const startedAtUtc=new Date().toISOString();need(time(startedAtUtc)<=time(admission.executionWindow.notAfterUtc),'Execution window expired');
  const contextFile=path.join(directory,'context.json');append(contextFile,config);
  const bootstrap=path.join(admission.repoRoot,'tools/release/captureBackendRuntimePreparedInputs31.cjs'),argumentsList=['--no-global-search-paths',bootstrap,'--config',contextFile];
  const start={schemaVersion:2,source:admission.source,approvalPointer:admission.approvalPointer,phase,functions:phaseNames(admission,phase),attempt:1,startedAtUtc,sourceBefore,executable:admission.runtime.nodeExecutable,nodeSha256:admission.runtime.nodeSha256,arguments:argumentsList,cliArguments:['deploy','--only',phaseNames(admission,phase).map(x=>'functions:'+x).join(','),'--project',admission.projectId,'--non-interactive'],cwd:admission.repoRoot,requiredProducerBindings:admission.requiredProducerBindings,requiredProposalBindings:admission.requiredProposalBindings,schedulerManuallyInvoked:false,businessProbePerformed:false,automaticRetryAllowed:false};append(path.join(directory,'attempt-start.json'),start);
  // Files exist before the sole child is started; exceptions preserve them.
  const stdoutFile=path.join(directory,'stdout.log'),stderrFile=path.join(directory,'stderr.log'),out=fs.openSync(stdoutFile,'wx',0o600),err=fs.openSync(stderrFile,'wx',0o600);
  let child,result;try{child=spawnSync(admission.runtime.nodeExecutable,argumentsList,{cwd:admission.repoRoot,env:e.cleanEnvironment31(),windowsHide:true,stdio:['ignore',out,err],timeout:Math.max(1,Number((time(admission.executionWindow.notAfterUtc)-time(new Date().toISOString()))/1000000n)),killSignal:'SIGTERM'});}catch(error){child={status:null,signal:null,error};}finally{fs.closeSync(out);fs.closeSync(err);}
  const completedAtUtc=new Date().toISOString();result={...start,completedAtUtc,exitCode:child.status,signal:child.signal??null,error:child.error?{code:child.error.code??null,message:child.error.message}:null,actualDeploymentPerformed:null,partialCloudMutationPossible:true,stdout:privateBinding(admission,stdoutFile),stderr:privateBinding(admission,stderrFile)};
  try{need(child.status===0&&!child.signal&&!child.error,'Deployment child failed; inspect preserved partial results before any new decision');const completionFile=path.join(directory,'instrumented-cli-complete.json'),completion=object(fs.readFileSync(completionFile));eq(completion.source,admission.source,'Instrumented completion source differs');eq(completion.approvalPointer,admission.approvalPointer,'Instrumented completion approval differs');need(completion.phase===phase&&completion.actualPreparationCaptured===true,'Actual preparation completion missing');
    const finalAdmission=e.verifyBackendRuntimeExecutionAdmission31(base);eq(finalAdmission.source,admission.source,'Postflight source differs');result={...result,sourceAfter:snapshot(finalAdmission),capture:completion.capture,archive:completion.archive,instrumentedCompletion:privateBinding(admission,completionFile),actualDeploymentPerformed:true,partialCloudMutationPossible:false};
  }catch(error){result.validationFailure=error.message;result.exitCode=result.exitCode===0?1:result.exitCode;}
  append(path.join(directory,'attempt-result.json'),result);need(result.exitCode===0,'Cohort did not close successfully; original outputs and partial attempt retained');return result;
}
if(require.main===module){try{need(process.argv.length===5&&['--plan','--execute'].includes(process.argv[2])&&process.argv[3]==='--config','Use --plan|--execute --config FILE only');const config=object(fs.readFileSync(process.argv[4])),result=process.argv[2]==='--execute'?executeBackendRuntime31(config):planBackendRuntimeExecution31(config);process.stdout.write(JSON.stringify(result,null,2)+'\n');}catch(error){process.stderr.write(error.message+'\n');process.exitCode=1;}}
module.exports={executeBackendRuntime31,planBackendRuntimeExecution31,verifyPriorPhases31,validateConfig,snapshot};
