# Starts the Firebase emulator suite for the CRM-III DEV loop.
#
# Run this in its own terminal and leave it running, then start the app with
# tool/dev/run_dev.ps1 in a second terminal.
#
# The project id must begin with "demo-": the emulator suite accepts any id,
# but a demo id cannot resolve to a real Firebase project, so a call that is
# somehow not routed to an emulator fails instead of reaching production.

$ErrorActionPreference = 'Stop'
Set-Location (Join-Path $PSScriptRoot '..\..')

$projectId = $env:CRM_DEMO_PROJECT_ID
if ([string]::IsNullOrWhiteSpace($projectId)) { $projectId = 'demo-crm3-baf-ops' }
if (-not $projectId.StartsWith('demo-')) {
  throw "CRM_DEMO_PROJECT_ID must start with 'demo-'. Received: $projectId"
}

$firebase = 'tooling/firebase-cli/node_modules/firebase-tools/lib/bin/firebase.js'
if (-not (Test-Path $firebase)) {
  throw "Governed Firebase CLI not installed. Run: npm --prefix tooling/firebase-cli ci --ignore-scripts"
}

# firebase-functions resolves CRM3_MUTATING_CALLABLE_ENFORCE_APP_CHECK at load
# time because callableSecurityConfig.ts reads it with .value() during
# deployment analysis. Without a value the emulator stops and prompts for it,
# which never completes unattended: no function registers and every callable
# fails NOT_FOUND. false is the source default, so this changes no behaviour.
#
# The file is deliberately not committed. functions/ is an approved artifact
# source path, so an extra file there makes the current source diverge from the
# deployed backend.
$paramsFile = "functions/.env.$projectId"
if (-not (Test-Path $paramsFile)) {
  Set-Content -Path $paramsFile -Encoding utf8 -Value @(
    '# Local emulator parameter values. Generated by tool/dev/emulators.ps1.',
    '# Not committed: see .gitignore.',
    'CRM3_MUTATING_CALLABLE_ENFORCE_APP_CHECK=false'
  )
  Write-Host "Wrote $paramsFile" -ForegroundColor DarkGray
}

Write-Host "Starting Auth + Firestore + Functions emulators for $projectId" -ForegroundColor Cyan
Write-Host "Emulator UI: http://127.0.0.1:4000" -ForegroundColor Cyan

node $firebase emulators:start --only auth,firestore,functions --project $projectId
