// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe_Bz7zowdJhWINJIRI9NyfpGCEtORzM8',
    appId: '1:894346496105:web:b7a8cff97a3a90a0e63af8',
    messagingSenderId: '894346496105',
    projectId: 'crm3-baf-ops-b8638',
    authDomain: 'crm3-baf-ops-b8638.firebaseapp.com',
    storageBucket: 'crm3-baf-ops-b8638.firebasestorage.app',
    measurementId: 'G-5P74FF3F2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL43OaEkn4VfsPd6-JVqme9BSxs5AdjKk',
    appId: '1:894346496105:android:fba14febfbbee102e63af8',
    messagingSenderId: '894346496105',
    projectId: 'crm3-baf-ops-b8638',
    storageBucket: 'crm3-baf-ops-b8638.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUVzIs26loj3qW3wTTSW6iVAWmBdWn_zk',
    appId: '1:894346496105:ios:d42c0a5b8c069c67e63af8',
    messagingSenderId: '894346496105',
    projectId: 'crm3-baf-ops-b8638',
    storageBucket: 'crm3-baf-ops-b8638.firebasestorage.app',
    iosBundleId: 'com.example.crm3BafOps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUVzIs26loj3qW3wTTSW6iVAWmBdWn_zk',
    appId: '1:894346496105:ios:d42c0a5b8c069c67e63af8',
    messagingSenderId: '894346496105',
    projectId: 'crm3-baf-ops-b8638',
    storageBucket: 'crm3-baf-ops-b8638.firebasestorage.app',
    iosBundleId: 'com.example.crm3BafOps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe_Bz7zowdJhWINJIRI9NyfpGCEtORzM8',
    appId: '1:894346496105:web:f8c70cf3c7c009cde63af8',
    messagingSenderId: '894346496105',
    projectId: 'crm3-baf-ops-b8638',
    authDomain: 'crm3-baf-ops-b8638.firebaseapp.com',
    storageBucket: 'crm3-baf-ops-b8638.firebasestorage.app',
    measurementId: 'G-WQ6E3PC9Q7',
  );
}
