'use strict';
// Synthetic Firestore-shaped infrastructure. Application functions are imported
// from current application output. Adapted from the supplied Function 09 evidence.
const path=require('node:path');const assert=require('node:assert/strict');const {randomUUID}=require('node:crypto');
const root=path.resolve(__dirname,'../..');const load=n=>require(path.join(root,'lib',n));const copy=x=>x===undefined?undefined:structuredClone(x);
function fakeDb(seed={}){
 const store=new Map(Object.entries(seed).map(([k,v])=>[k,copy(v)])),writes=[],reads=[];
 let auto=0,tail=Promise.resolve();
 const snap=p=>({exists:store.has(p),id:p.split('/').at(-1),data:()=>copy(store.get(p))});
 const getField=(d,f)=>f.split('.').reduce((v,k)=>v?.[k],d);
 function query(name,filters=[],max=Infinity,order=null,after=null){return {
  where(f,op,v){return query(name,[...filters,{f,op,v}],max,order,after)},
  orderBy(f,direction='asc'){return query(name,filters,max,{f,direction},after)},
  startAfter(s){return query(name,filters,max,order,s.id)},limit(n){return query(name,filters,n,order,after)},
  async get(){reads.push({query:name,filters:copy(filters)});let rows=[...store].filter(([p,d])=>p.startsWith(name+'/')&&!p.slice(name.length+1).includes('/')&&filters.every(({f,op,v})=>{
   const a=getField(d,f);switch(op){case'==':return JSON.stringify(a)===JSON.stringify(v);case'in':return v.includes(a);case'array-contains':return Array.isArray(a)&&a.includes(v);case'<=':return a<=v;case'<':return a<v;case'>=':return a>=v;case'>':return a>v;case'!=':return a!==undefined&&a!==v;default:throw Error('Unsupported query '+op)}}));
   if(order)rows.sort(([pa,a],[pb,b])=>{let av=order.f==='__name__'?pa:getField(a,order.f),bv=order.f==='__name__'?pb:getField(b,order.f);return (av<bv?-1:av>bv?1:pa.localeCompare(pb))*(order.direction==='desc'?-1:1)});
   if(after)rows=rows.filter(([p])=>p.split('/').at(-1)>after);return{docs:rows.slice(0,max).map(([p])=>snap(p))};}
 }}
 const db={collection(name){return{...query(name),doc(id){if(id===undefined)id='generated_'+(++auto);const p=name+'/'+id;return{id,path:p,async get(){reads.push({path:p});return snap(p)}}}}},
 async runTransaction(fn){let release;const prev=tail;tail=new Promise(r=>release=r);await prev;
 const staged=[];let writing=false;
 try{const tx={async get(r){if(writing)throw Error('audit-read-after-write');return r.get()},set(r,d,o){writing=true;staged.push({path:r.path,data:copy(d),merge:o?.merge===true})},delete(r){writing=true;staged.push({path:r.path,delete:true})}};
 const value=await fn(tx);const next=new Map([...store].map(([p,v])=>[p,copy(v)]));for(const w of staged){if(w.delete)next.delete(w.path);else next.set(w.path,w.merge?{...next.get(w.path),...copy(w.data)}:copy(w.data))}store.clear();for(const [p,v]of next)store.set(p,v);writes.push(...staged);return value;}finally{release()}
 }};return{db,store,writes,reads};
}
function workflowReadTransaction(a, fn) {
 return a.db.runTransaction(async tx => fn({
  async get(p) { const [c,id]=p.split('/'); const row=await tx.get(a.db.collection(c).doc(id)); return {path:p, exists:row.exists,data:row.data()??null}; },
  async query(c, filters) {let q=a.db.collection(c);for(const f of filters)q=q.where(f.field,f.op,f.value);const page=await tx.get(q);return page.docs.map(s=>({path:c+'/'+s.id,exists:s.exists,data:s.data()??null}));}
 }));
}
const users={'users/admin':{name:'Synthetic Admin',roles:['admin'],isApproved:true},'users/si':{name:'Synthetic SI',roles:['si'],isApproved:true},'users/ops':{name:'Synthetic Operations',roles:['operations'],isApproved:true},'users/mech':{name:'Synthetic Mechanical',roles:['seniorMechanical'],isApproved:true},'users/no':{name:'Unapproved',roles:['admin'],isApproved:false}};
function assets(){return{'asset_classes/class-furnace':{schemaVersion:1,assetClassId:'class-furnace',code:'FR',name:'Furnace',legacyAssetTypeKey:'furnace',status:'active',version:1,isDeleted:false},'asset_instances/furnace-7':{schemaVersion:1,assetInstanceId:'furnace-7',assetClassId:'class-furnace',assetClassCode:'FR',assetClassName:'Furnace',assetNumber:7,name:'Furnace 7',status:'active',serviceState:'inService',version:4,isDeleted:false,ownershipStatus:'confirmed',ownerDiscipline:'Mechanical',accountableRoleKeys:['seniorMechanical']},'asset_hierarchy_nodes/shell':{schemaVersion:1,nodeId:'shell',assetClassId:'class-furnace',status:'active',version:3,nodeType:'component',name:'Furnace shell',componentTag:'SH-7',hierarchyPath:['Structure','Furnace shell'],ownershipStatus:'confirmed',ownerDiscipline:'Mechanical',accountableRoleKeys:['seniorMechanical']},'asset_component_instances/installed-shell':{schemaVersion:1,componentInstanceId:'installed-shell',assetClassId:'class-furnace',assetInstanceId:'furnace-7',assetNumber:7,definitionNodeId:'shell',definitionNodeVersion:3,assetInstanceVersionAtMutation:4,componentTag:'SH-7',status:'active',version:1,ownershipStatus:'confirmed',ownerDiscipline:'Mechanical',accountableRoleKeys:['seniorMechanical']}}}
function ref(scope='installedComponent'){return{schemaVersion:scope==='definition'?1:2,scope,assetClassId:'class-furnace',assetClassCode:'FR',assetClassName:'Furnace',nodeId:'shell',nodeVersion:3,nodeName:'Furnace shell',assetInstanceId:scope==='definition'?null:'furnace-7',assetInstanceVersion:scope==='definition'?null:4,assetNumber:scope==='definition'?null:7,assetInstanceName:scope==='definition'?null:'Furnace 7',componentInstanceId:scope==='definition'?null:'installed-shell',componentInstanceVersion:scope==='definition'?null:1,componentTag:scope==='definition'?null:'SH-7',hierarchyPath:['Structure','Furnace shell'],ownershipStatus:'confirmed',ownerDiscipline:'Mechanical',accountableRoleKeys:['seniorMechanical']}}
const assignment=load('publishedTemplateAssignment');
function V(overrides={}){const v={firestoreId:'version-1',packageFirestoreId:'package-1',versionNumber:1,versionLabel:'v1',status:'published',jobTemplateSnapshotJson:JSON.stringify({jobName:'Synthetic Furnace PM',assetType:'furnace',composer:{closureReviewConfirmed:true,closureReviewConfirmedByUid:'si',closureReviewConfirmedByName:'Synthetic SI',closureReviewConfirmedAt:'2026-09-19T04:00:00.000Z'},closureCriticalCount:1}),moduleSnapshotsJson:JSON.stringify([{moduleCode:'M-01',moduleTitle:'Inspect shell',isRequired:true,requiredForClosure:true,discipline:'mechanical'}]),fieldDefinitionsJson:JSON.stringify([{key:'reading',label:'Reading',moduleCode:'M-01',type:'number',isRequired:true}]),checklistJson:'[]',closureReviewConfirmed:true,closureCriticalModuleCount:1,closureReviewConfirmedByUid:'si',closureReviewConfirmedByName:'Synthetic SI',closureReviewConfirmedAt:'2026-09-19T04:00:00.000Z',publishedByUid:'si',publishedByName:'Synthetic SI',publishedAt:'2026-09-19T04:05:00.000Z',targetRefs:[],deviceTagRefs:[],safetyClass:null,safetyGatePolicyJson:null,procedureRefs:[],operationalStatePreconditions:[],schemaVersion:1,isDeleted:false,...overrides};v.contentHash=assignment.computeTemplateVersionContentHash(v);return v}
function A(overrides={}){const version=V(overrides.version||{});const a=fakeDb({...users,...assets(),'template_packages/package-1':{firestoreId:'package-1',packageCode:'FR-PM',title:'Furnace PM',disciplineScope:'mechanical',lifecycleStatus:'active',activeVersionFirestoreId:'version-1',latestVersionNumber:1,isDeleted:false,...overrides.package},'template_versions/version-1':version,'template_publish_audits/publication-1':{firestoreId:'publication-1',packageFirestoreId:'package-1',versionFirestoreId:'version-1',action:'published',performedByUid:'si',performedAt:'2026-09-19T04:05:01.000Z',afterHash:version.contentHash,isDeleted:false},'equipment_prompt_master/fr':{assetTypeKey:'furnace',active:true,redSuccessorTemplateCode:'FR-PM'},...overrides.seed});a.now='2026-09-20T04:00:00.000Z';a.actor='admin';a.request={requestId:randomUUID(),packageId:'package-1',versionId:'version-1',expectedVersionNumber:1,expectedContentHash:version.contentHash,assetType:'furnace',assetNumber:7,chargeNoAtEvent:null,remarks:'Synthetic assignment'};a.assign=(data=a.request,extras={})=>assignment.assignPublishedTemplateVersionWithDb({db:a.db,authUid:a.actor,data,now:()=>new Date(a.now),...extras});a.red=()=>workflowReadTransaction(a,tx=>load('maintenanceWorkflow/redSuccessorTemplateResolver').resolveRedSuccessorTemplate(tx,{assetTypeKey:'furnace',assetNumber:7,assetClassId:'class-furnace',assetInstanceId:'furnace-7'}));return a}
async function result(fn){try{return{accepted:true,value:await fn()}}catch(e){return{accepted:false,code:e.code,reason:e.details?.reasonCode,message:e.message,details:e.details}}}
module.exports={root,load,assert,randomUUID,copy,fakeDb,workflowReadTransaction,users,assets,ref,V,A,assignment,result};
